---
sidebar: sidebar 
permalink: concept-licensing-charging.html 
keywords: capacity-based license charging, consumption for licenses, pricing for licenses, CVO licensing, CVO charging, SnapLock charging, CIFS charging, audit volumes, primary volumes, volume-based charging 
summary: Machen Sie sich mit der Abrechnung, dem Verbrauchsmodell, den Preisen und den Konfigurationen kapazitätsbasierter Lizenzen vertraut. 
---
= Erfahren Sie mehr über kapazitätsbasierte Lizenzen für Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die kapazitätsbasierte Lizenzierung von Cloud Volumes ONTAP legt fest, wie Speicherkapazität, Pakete und Überschreitungen abgerechnet werden. Diese Informationen bieten einen Überblick über die Abrechnung und den Kapazitätsverbrauch, insbesondere bei Bereitstellungen im Standardmodus.

Für Bereitstellungen im privaten Modus können kapazitätsbasierte Essentials-Pakete nur im Rahmen eines Bring-Your-Own-Lizenzmodells (BYOL) verwendet werden. Details zur Lizenzierung von Bereitstellungen im privaten Modus finden sich unter link:concept-license-management.html["Informationen zu Cloud Volumes ONTAP BYOL"^].



[[consumption-models-and-purchase-options]]
== Konsummodelle und Kaufoptionen

Kapazitätsbasierte Lizenzpakete sind mit folgenden Verbrauchsmodellen bzw. Kaufoptionen erhältlich:

* *Marketplace-Abonnements/Jahresvertrag*: Ein Jahresvertrag vom Marketplace Ihres Cloud-Anbieters. Bereitstellungen im Private-Mode unterstützen keine Marketplace-Abonnements.
* *PAYGO*: Ein Pay-as-you-go-Abonnement (PAYGO) ist ein stündliches Abonnement vom Marktplatz Ihres Cloud-Anbieters.
* *BYOL*: Bring-Your-Own-License (BYOL). Eine von NetApp erworbene Lizenz, die zur Bereitstellung von Cloud Volumes ONTAP bei jedem Cloud-Anbieter verwendet werden kann.
+

NOTE: NetApp hat den Kauf, die Erweiterung und die Erneuerung von BYOL-Lizenzen eingeschränkt und die Verfügbarkeit in bestimmten Szenarien, wie zum Beispiel bei Bereitstellungen im privaten Modus, begrenzt. Weitere Informationen sind unter  https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html#restricted-availability-of-byol-licensing-for-cloud-volumes-ontap["Eingeschränkte Verfügbarkeit der BYOL-Lizenzierung für Cloud Volumes ONTAP"^] zu finden.



Beachten Sie Folgendes:

* Wenn Sie eine BYOL-Lizenz von NetApp erwerben, ist zusätzlich ein Abonnement des PAYGO-Angebots im Marketplace Ihres Cloud-Anbieters erforderlich. NetApp hat die BYOL-Lizenzierung für Bereitstellungen im Standardmodus eingeschränkt. Nach Ablauf Ihrer BYOL-Lizenz erfolgt der Wechsel zu einem Abonnement im Cloud Marketplace.
+
Ihre Lizenz wird immer zuerst in Rechnung gestellt. In den folgenden Fällen wird Ihnen jedoch der Stundensatz auf dem Marktplatz in Rechnung gestellt:

+
** Wenn Sie Ihre lizenzierte Kapazität überschreiten
** Wenn die Laufzeit Ihrer Lizenz abläuft


* Wenn Sie eine BYOL-Lizenz und einen Jahresvertrag von einem Marktplatz besitzen, werden Ihr Verbrauch und etwaige Mehrkosten gemäß der von Ihnen festgelegten Abrechnungspräferenz berechnet. Um zu verstehen, wie Sie abgerechnet werden, siehe link:concept-licensing-charging.html#billing-preferences-and-overages["Abrechnungseinstellungen und Überschreitungen"].
* Nur Einzelknotensysteme mit BYOL werden in China-Regionen unterstützt. Bereitstellungen in China-Regionen sind von den BYOL-Lizenzbeschränkungen ausgenommen.




[[how-you-are-charged-for-supported-storage-types-and-packages]]
== Wie Ihnen die unterstützten Speichertypen und Pakete in Rechnung gestellt werden

Die Abrechnung in Cloud Volumes ONTAP basiert auf einer Reihe von Faktoren, wie z. B. Paketen und Volumentypen. Kapazitätsbasierte Lizenzpakete sind mit Cloud Volumes ONTAP 9.7 und höher verfügbar.

Die folgenden Abschnitte erläutern, welche Kosten anfallen, wo Mindestbeträge gelten und wie Mehrkosten abgerechnet werden.

Weitere Informationen zur Preisgestaltung finden Sie auf der  https://bluexp.netapp.com/pricing/["NetApp Console Website"^].



[[storage-vms]]
=== Speicher-VMs

* Für zusätzliche datenverarbeitende Storage-VMs (SVMs) fallen keine zusätzlichen Lizenzkosten an, allerdings wird eine Mindestkapazität von vier TiB pro datenverarbeitender Storage-VM berechnet.
* Die Kosten für Disaster Recovery-SVMs richten sich nach der bereitgestellten Kapazität.




[[ha-pairs]]
=== HA-Paare

Bei HA-Paaren wird Ihnen nur die bereitgestellte Kapazität auf einem Knoten in Rechnung gestellt.  Für Daten, die synchron auf den Partnerknoten gespiegelt werden, fallen keine Kosten an.



[[flexclone-and-flexcache-volumes]]
=== FlexClone und FlexCache -Volumes

* Für die von FlexClone -Volumes genutzte Kapazität werden Ihnen keine Kosten berechnet.
* Quell- und Ziel- FlexCache -Volumes werden als Primärdaten betrachtet und entsprechend dem bereitgestellten Speicherplatz berechnet.




[[readwrite-volumes]]
=== Lese-/Schreibvolumes

Ein beschreibbares (lesen/schreiben) Volume ist ein primäres Volume. Das System berechnet die bereitgestellte Kapazität anhand des Mindestpreises pro Storage VM (SVM). Beispiele sind FlexVol lesen/schreiben Volumes, SnapLock Audit Volumes und CIFS/NFS Audit Volumes. Alle vom Benutzer erstellten Datenvolumes werden entsprechend dem Abonnement und dem Pakettyp abgerechnet. ONTAP interne Volumes, wie SVM Root Volumes, werden nicht berechnet, da sie automatisch erstellt werden und keine Daten speichern können.



[[essentials-packages]]
=== Essentials-Pakete

Das Essentials Paket wird nach Bereitstellungstyp (HA oder Einzelknoten) und Volumentyp (primär oder sekundär) abgerechnet. Die Preise von hoch nach niedrig sind Essentials Primary HA, Essentials Primary Single Node, Essentials Secondary HA und Essentials Secondary Single Node. Beim Kauf eines Marketplace-Vertrags oder bei Annahme eines privaten Angebots ist die Kapazitätsgebühr für jeden Bereitstellungs- oder Volumentyp gleich.

Die Lizenzierung basiert vollständig auf dem Volume-Typ, der in Cloud Volumes ONTAP Systemen erstellt wird:

* Essentials Single Node: Lese-/Schreib-Volumes, die auf einem Cloud Volumes ONTAP System mit nur einem ONTAP Knoten erstellt wurden.
* Essentials HA: Lese-/Schreib-Volumes mit zwei ONTAP -Knoten, die für einen unterbrechungsfreien Datenzugriff auf einander umschalten können.
* Essentials Secondary Single Node: Volumes vom Typ Data Protection (DP) (normalerweise schreibgeschützte SnapMirror oder SnapVault -Zielvolumes), die auf einem Cloud Volumes ONTAP System unter Verwendung nur eines ONTAP Knotens erstellt wurden.
+

NOTE: Wenn ein schreibgeschütztes DP-Volume zu einem primären Volume wird, behandelt die Console es als primäre Daten und berechnet die Gebühren basierend auf der Zeit, in der sich das Volume im lesen/schreiben-Modus befindet. Wenn das Volume wieder schreibgeschützt wird, behandelt die Console es als sekundäre Daten und berechnet die Gebühren entsprechend der am besten passenden Lizenz in der Console.

* Essentials Secondary HA: Volumes vom Typ Data Protection (DP) (normalerweise schreibgeschützte SnapMirror oder SnapVault -Zielvolumes), die auf einem Cloud Volumes ONTAP -System unter Verwendung von zwei ONTAP Knoten erstellt werden, die für einen unterbrechungsfreien Datenzugriff auf einander umschalten können.




[[minimum-charge]]
== Mindestgebühr

Für jede datenbereitstellende Speicher-VM mit mindestens einem primären (Lese-/Schreib-)Volume wird eine Mindestgebühr von 4 TiB erhoben.  Wenn die Summe der primären Volumes weniger als 4 TiB beträgt, berechnet die Konsole dieser Speicher-VM die Mindestgebühr von 4 TiB.

Wenn Sie noch keine Volumes bereitgestellt haben, fällt die Mindestgebühr nicht an.

Beim Essentials-Paket fällt die Gebühr für die Mindestkapazität von 4 TiB nicht für Speicher-VMs an, die nur sekundäre (Datenschutz-)Volumes enthalten. Wenn Sie beispielsweise über eine Speicher-VM mit 1 TiB sekundärer Daten verfügen, werden Ihnen nur die Kosten für dieses 1 TiB Daten in Rechnung gestellt. Beim Pakettyp „Professional“ gilt unabhängig vom Volume-Typ die Mindestkapazitätsberechnung von 4 TiB.



[[billing-preferences-and-overages]]
== Abrechnungseinstellungen und Überschreitungen

Im Abschnitt * Licenses and subscriptions* in der Konsole können Sie auswählen, wie die Abrechnung erfolgen soll. Überschreitungen entstehen, wenn Ihre Nutzung die in Ihrem Lizenzpaket oder Jahresabonnement festgelegte Kapazität überschreitet.

* * NetApp -Lizenzen zuerst*: Bei diesem Modell wird Ihre Nutzung zunächst auf die Kapazität Ihres Lizenzpakets (BYOL) angerechnet. Wenn Sie Ihre Lizenzkapazität überschreiten, werden die Mehrkosten auf Basis Ihres jährlichen Marktplatz-Abonnements oder Ihrer stündlichen Marktplatz-Abrechnungssätze (PAYGO) berechnet. Wenn Ihre BYOL-Lizenz abläuft, müssen Sie über die Cloud-Marktplätze auf ein kapazitätsbasiertes Lizenzierungsmodell umsteigen. Weitere Informationen finden Sie unter link:task-convert-node-capacity.html["Konvertieren Sie eine knotenbasierte Cloud Volumes ONTAP -Lizenz in eine kapazitätsbasierte Lizenz"]Die
* *Nur für Marketplace-Abonnements*: Bei diesem Modell wird Ihre Nutzung zunächst über Ihr jährliches Marketplace-Abonnement abgerechnet. Jegliche zusätzliche Nutzung wird zu den stundenweisen On-Demand-Tarifen des Marktplatzes abgerechnet (PAYGO). Nicht genutzte Lizenzkapazität wird bei der Abrechnung nicht berücksichtigt.


Weitere Informationen zu den Abrechnungseinstellungen finden Sie unter https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html["Erfahren Sie mehr über die Abrechnungseinstellungen für Lizenzen und Abonnements."^]Die



[[how-overages-are-charged-for-essentials-licenses]]
=== Wie Überschreitungen bei Essentials-Lizenzen abgerechnet werden

Wenn Sie eine Essentials-Lizenz von NetApp (BYOL) erwerben und die lizenzierte Kapazität für ein bestimmtes Essentials-Paket überschreiten, berechnet die Console die Mehrkosten einer höherpreisigen Essentials-Lizenz (sofern Sie über eine solche mit verfügbarer Kapazität verfügen).  Die Konsole nutzt zunächst die verfügbare Kapazität, für die Sie bezahlt haben, bevor sie den Marktplatz in Rechnung stellt.  Falls mit Ihrer BYOL-Lizenz keine Kapazität verfügbar ist, wird die überschrittene Kapazität zu den stündlichen On-Demand-Tarifen des Marktplatzes (PAYGO) abgerechnet und Ihrer monatlichen Rechnung hinzugefügt.

Wenn Sie beispielsweise einen Jahresvertrag über den Marktplatz oder ein privates Angebot mit mehreren Essentials Paketen haben und Ihre Nutzung die zugesicherte Kapazität für einen bestimmten Bereitstellungs- und Volumentyp überschreitet, werden die Mehrkosten von der Konsole einem höherpreisigen Essentials Paket mit verfügbarer Kapazität zugeordnet. Sobald diese Kapazität erschöpft ist, wird der verbleibende Mehrverbrauch zu den stündlichen On-Demand-Tarifen (PAYGO) des Marktplatzes abgerechnet und Ihrer monatlichen Rechnung hinzugefügt.

Informationen zu den Gebühren für Essentials-Lizenzen sind unter <<Essentials-Pakete>> zu finden.

Hier ist ein Beispiel. Angenommen, Sie verfügen über die folgenden Lizenzen für das Essentials-Paket:

* Eine 500 TiB _Essentials Secondary HA_-Lizenz mit 500 TiB zugesicherter Kapazität
* Eine 500 TiB _Essentials Single Node_-Lizenz mit nur 100 TiB zugesicherter Kapazität


Weitere 50 TiB werden auf einem HA-Paar mit sekundären Volumes bereitgestellt.  Anstatt diese 50 TiB PAYGO in Rechnung zu stellen, verrechnet die Konsole die 50 TiB Überschreitung mit der _Essentials Single Node_-Lizenz.  Diese Lizenz ist teurer als _Essentials Secondary HA_, nutzt jedoch eine Lizenz, die Sie bereits erworben haben, und verursacht keine zusätzlichen Kosten auf Ihrer monatlichen Rechnung.

Unter *Verwaltung > Licenses and subscriptions* können Sie sehen, dass 50 TiB von der _Essentials Single Node_-Lizenz abgezogen werden.

Hier ist ein weiteres Beispiel.  Angenommen, Sie verfügen über die folgenden Lizenzen für das Essentials-Paket:

* Eine 500 TiB _Essentials Secondary HA_-Lizenz mit 500 TiB zugesicherter Kapazität
* Eine 500 TiB _Essentials Single Node_-Lizenz mit nur 100 TiB zugesicherter Kapazität


Weitere 100 TiB werden auf einem HA-Paar mit primären Volumes bereitgestellt.  Die von Ihnen erworbene Lizenz verfügt nicht über die zugesagte Kapazität von _Essentials Primary HA_.  Die Lizenz „Essentials Primary HA“ ist teurer als die Lizenzen „Essentials Primary Single Node“ und „Essentials Secondary HA“.

In diesem Beispiel berechnet die Konsole für die zusätzlichen 100 TiB Überschreitungen zum Marktpreis.  Die Überschreitungsgebühren werden auf Ihrer monatlichen Rechnung erscheinen.



[[change-license-packages]]
== Lizenzpakete ändern

Nach der Bereitstellung kann das Paket für ein Cloud Volumes ONTAP System mit kapazitätsbasierter Lizenzierung geändert werden. Wenn beispielsweise ein Cloud Volumes ONTAP System mit dem Essentials Paket bereitgestellt wurde, ist bei geänderten Geschäftsanforderungen ein Wechsel zum Professional Paket möglich. link:task-manage-capacity-licenses.html["Erfahren Sie, wie Sie die Lademethode ändern"].

NetApp stellt die knotenbasierte Lizenzierung zugunsten der kapazitätsbasierten Lizenzierung schrittweise ein. Knotenbasierte Lizenzen sind weiterhin in einigen älteren Systemen verfügbar, beispielsweise bei USPS-Kunden und in Installationen in China. Bei Vorliegen einer knotenbasierten Lizenz ist eine Umwandlung in eine kapazitätsbasierte Lizenzierung möglich. Informationen zur Umwandlung von knotenbasierten Lizenzen in kapazitätsbasierte Lizenzierung finden sich unter link:task-convert-node-capacity.html["Konvertieren Sie eine knotenbasierte Lizenz in eine kapazitätsbasierte Lizenz"].



[[capacity-limit]]
== Kapazitätsgrenze

Im kapazitätsbasierten Lizenzmodell unterstützt jedes Cloud Volumes ONTAP System die Einstufung in Objektspeicher und die gesamte abgestufte Kapazität kann bis zum Bucket-Limit des Cloud-Anbieters skaliert werden. Obwohl die Lizenz keine Kapazitätsbeschränkungen vorsieht, befolgen Sie die https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Best Practices für FabricPool"^] um optimale Leistung, Zuverlässigkeit und Kosteneffizienz bei der Konfiguration und Verwaltung der Tiering-Ebene sicherzustellen.

Informationen zu den Kapazitätsgrenzen der einzelnen Cloud-Anbieter finden Sie in deren Dokumentation:

* https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html["AWS-Dokumentation"^]
* https://learn.microsoft.com/en-us/azure/storage/common/scalability-targets-standard-account["Azure-Dokumentation für verwaltete Datenträger"^]Und https://learn.microsoft.com/en-us/azure/storage/blobs/scalability-targets["Azure-Dokumentation für Blob Storage"^]
* https://cloud.google.com/storage/docs/buckets["Google Cloud-Dokumentation"^]




[[max-number-of-systems]]
== Maximale Anzahl an Systemen

Die kapazitätsbasierte Lizenzierung beschränkt jede NetApp Console Organisation auf 24 Cloud Volumes ONTAP Systeme. Ein System kann ein Cloud Volumes ONTAP HA Paar, ein Cloud Volumes ONTAP Einzelknotensystem oder eine zusätzliche Storage-VM sein, die erstellt wird. Die Standard-Storage-VM wird nicht auf das Limit angerechnet. Dieses Limit gilt für alle Lizenzmodelle.

Nehmen wir beispielsweise an, Sie haben drei Systeme:

* Ein Cloud Volumes ONTAP -System mit einem Knoten und einer Speicher-VM (dies ist die Standard-Speicher-VM, die beim Bereitstellen von Cloud Volumes ONTAP erstellt wird)
+
Dieses System zählt als ein System.

* Ein Cloud Volumes ONTAP -System mit einem Knoten und zwei Speicher-VMs (die Standard-Speicher-VM plus eine zusätzliche Speicher-VM, die Sie erstellt haben)
+
Dieses System zählt als zwei Systeme: eines für das Einzelknotensystem und eines für die zusätzliche Storage-VM.

* Ein Cloud Volumes ONTAP HA-Paar mit drei Storage-VMs (die Standard-Storage-VM plus zwei zusätzliche Storage-VMs, die Sie erstellt haben)
+
Dieses System zählt als drei Systeme: eines für das HA-Paar und zwei für die zusätzlichen Speicher-VMs.



Das sind insgesamt sechs Systeme. Sie hätten dann Platz für weitere 14 Systeme in Ihrer Organisation.

Bei größeren Installationen mit mehr als 24 Systemen ist der Kundenbetreuer oder das Vertriebsteam zu kontaktieren.

Informationen zu Speichergrenzen für:

* AWS: link:reference-limits-aws.html["Speicherlimits für Cloud Volumes ONTAP in AWS"]
* Azure: link:reference-limits-azure.html["Speicherlimits für Cloud Volumes ONTAP in Azure"]
* Google Cloud: link:reference-limits-gcp.html["Speichergrenzen für Cloud Volumes ONTAP in Google Cloud"]


.Weiterführende Links
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html["Lizenzierung für Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-capacity-licenses.html["Verwalten Sie die kapazitätsbasierte Lizenzierung für Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-node-licenses.html["Knotenbasierte Lizenzierung verwalten"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-convert-node-capacity.html["Konvertieren Sie eine knotenbasierte Lizenz in eine kapazitätsbasierte Lizenz"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-keystone.html["Keystone -Abonnements verwalten"^]

