---
sidebar: sidebar 
permalink: concept-storage-management.html 
keywords: provisioning, capacity management, storage provisioning, manual, automatic, advanced allocation, aggregates, thin provisioning, free space, mode, BlueXP, NetApp Consolecloud manager 
summary: Die Konsole bietet eine vereinfachte und erweiterte Verwaltung des Cloud Volumes ONTAP Speichers. 
---
= Cloud Volumes ONTAP -Speicherverwaltung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die NetApp Console bietet eine vereinfachte und erweiterte Verwaltung des Cloud Volumes ONTAP Speichers.


CAUTION: Sie müssen alle Datenträger und Aggregate direkt von der Konsole aus erstellen und löschen. Sie sollten diese Aktionen nicht von einem anderen Verwaltungstool aus durchführen. Dies kann die Systemstabilität beeinträchtigen, die Möglichkeit, in Zukunft Festplatten hinzuzufügen, einschränken und möglicherweise zu überflüssigen Gebühren des Cloud-Anbieters führen.



[[storage-provisioning]]
== Speicherbereitstellung

Die Konsole vereinfacht die Speicherbereitstellung für Cloud Volumes ONTAP, indem sie Festplatten kauft und Aggregate für Sie verwaltet.  Sie müssen nur Volumes erstellen.  Sie können eine erweiterte Zuordnungsoption verwenden, um Aggregate selbst bereitzustellen, wenn Sie möchten.



[[simplified-provisioning]]
=== Vereinfachte Bereitstellung

Aggregate stellen Cloud-Speicher für Volumes bereit.  Die Konsole erstellt Aggregate für Sie, wenn Sie eine Instanz starten und zusätzliche Volumes bereitstellen.

Wenn Sie ein Volume erstellen, führt die Konsole eine von drei Aktionen aus:

* Es platziert das Volume auf einem vorhandenen Aggregat, das über ausreichend freien Speicherplatz verfügt.
* Es platziert das Volume auf einem vorhandenen Aggregat, indem es weitere Festplatten für dieses Aggregat kauft.
* Es kauft Festplatten für ein neues Aggregat und platziert das Volume auf diesem Aggregat.


Die Konsole ermittelt anhand mehrerer Faktoren, wo ein neues Volume platziert werden soll: der maximalen Größe eines Aggregats, der Aktivierung von Thin Provisioning und den Schwellenwerten für den freien Speicherplatz von Aggregaten.



[[advanced-allocation]]
=== Erweiterte Zuordnung

Sie können auch Aggregate verwalten. link:task-create-aggregates.html["Von der Seite *Erweiterte Zuordnung*"] können Sie neue Aggregate erstellen, die eine bestimmte Anzahl von Datenträgern enthalten, Datenträger zu einem vorhandenen Aggregat hinzufügen und Volumes in bestimmten Aggregaten erstellen.



[[capacity-management]]
== Kapazitätsmanagement

Der Organisations- oder Kontoadministrator kann die Konsole so konfigurieren, dass Sie über Entscheidungen zur Speicherkapazität benachrichtigt werden oder ob die Kapazitätsanforderungen automatisch für Sie verwaltet werden sollen.

Dieses Verhalten wird durch den _Kapazitätsverwaltungsmodus_ auf einem Konsolenagenten bestimmt.  Der Kapazitätsverwaltungsmodus wirkt sich auf alle Cloud Volumes ONTAP Systeme aus, die von diesem Konsolenagenten verwaltet werden.  Wenn Sie einen anderen Konsolenagenten haben, kann dieser anders konfiguriert werden.



[[automatic-capacity-management]]
=== Automatisches Kapazitätsmanagement

Der Kapazitätsverwaltungsmodus ist standardmäßig auf „Automatisch“ eingestellt.  In diesem Modus überprüft die Konsole alle 15 Minuten das Verhältnis des freien Speicherplatzes, um festzustellen, ob das Verhältnis des freien Speicherplatzes unter den angegebenen Schwellenwert fällt.  Wenn mehr Kapazität benötigt wird, leitet es den Kauf neuer Festplatten ein, löscht nicht verwendete Festplattensammlungen (Aggregate), verschiebt Volumes nach Bedarf zwischen Aggregaten und versucht, Festplattenausfälle zu verhindern.

Die folgenden Beispiele veranschaulichen die Funktionsweise dieses Modus:

* Wenn ein Aggregat die Kapazitätsschwelle erreicht und Platz für weitere Festplatten hat, kauft die Konsole automatisch neue Festplatten für dieses Aggregat, damit die Volumes weiter wachsen können.
* Wenn ein Aggregat die Kapazitätsschwelle erreicht und keine weiteren Festplatten mehr aufnehmen kann, verschiebt die NetApp Console automatisch ein Volume von diesem Aggregat auf ein Aggregat mit verfügbarer Kapazität oder auf ein neues Aggregat.
+
Wenn die Konsole ein neues Aggregat für das Volume erstellt, wählt sie eine Festplattengröße, die der Größe dieses Volumes entspricht.

+
Beachten Sie, dass auf dem ursprünglichen Aggregat nun freier Speicherplatz verfügbar ist. Bestehende Volumes oder neue Volumes können diesen Speicherplatz nutzen. Der Speicherplatz kann in diesem Szenario nicht an den Cloud-Provider zurückgegeben werden.

* Wenn ein Aggregat länger als 12 Stunden keine Volumes enthält, wird es von der Konsole gelöscht.




==== Verwaltung von LUNs mit automatischer Kapazitätsverwaltung

Die automatische Kapazitätsverwaltung der Konsole gilt nicht für LUNs.  Beim Erstellen einer LUN wird die Autogrow-Funktion deaktiviert.



[[manual-capacity-management]]
=== Manuelles Kapazitätsmanagement

Wenn der Organisations- oder Kontoadministrator den *Kapazitätsverwaltungsmodus* auf manuell einstellt, werden Sie von der Konsole aufgefordert, geeignete Maßnahmen für Kapazitätsentscheidungen zu ergreifen. Für den manuellen Modus gelten die gleichen Beispiele wie für den automatischen Modus, aber es liegt an Ihnen, die Aktionen zu akzeptieren.

.Weiterführende Links
* link:task-manage-capacity-settings.html["Erfahren Sie, wie Sie den Kapazitätsverwaltungsmodus ändern"] .
* Weitere Informationen zur Informationsbereitstellung in AWS sind unter link:reference-configs-aws.html["Festplattenbereitstellung für Aggregate in AWS"] zu finden.

