---
settings:
  name: Cloud Volumes ONTAP
  harmony_integration: maestro
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: Cloud-Anbieter
    default: Alle Cloud-Anbieter
    options:
    - name: Amazon Web Services
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azurblau
      id: azure
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Cloud Volumes ONTAP Dokumente
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
    - title: Bekannte Einschränkungen
      url: "/reference-limitations.html"
    - title: Versionshinweise zu Cloud Volumes ONTAP
      url: "/whats-new-ontap.html"
  - title: Erste Schritte
    entries:
    - title: Erfahren Sie mehr über Cloud Volumes ONTAP
      url: "/concept-overview-cvo.html"
    - title: Unterstützte ONTAP -Versionen für neue Bereitstellungen
      url: "/reference-versions.html"
    - title: Erste Schritte mit Amazon Web Services
      flavor: aws
      entries:
      - title: Schnellstart
        url: "/task-getting-started-aws.html"
      - title: Planen Sie Ihre Konfiguration
        url: "/task-planning-your-config.html"
      - title: Richten Sie Ihr Netzwerk ein
        entries:
        - title: Einrichten des AWS-Netzwerks
          url: "/reference-networking-aws.html"
        - title: Einrichten eines AWS Transit Gateways
          url: "/task-setting-up-transit-gateway.html"
        - title: Bereitstellen eines HA-Paares in einem gemeinsam genutzten Subnetz
          url: "/task-deploy-aws-shared-vpc.html"
        - title: Konfigurieren Sie Cloud Volumes ONTAP für die Erstellung von AWS-Platzierungsgruppen
          url: "/task-configure-placement-group-failure-aws.html"
        - title: Sicherheitsgruppenregeln für AWS
          url: "/reference-security-groups.html"
      - title: Einrichten des AWS KMS
        url: "/task-setting-up-kms.html"
      - title: Einrichten von IAM-Rollen
        url: "/task-set-up-iam-roles.html"
      - title: Einrichten der Lizenzierung
        url: "/task-set-up-licensing-aws.html"
      - title: Verwenden Sie die Schnellbereitstellungsmethode für Cloud Volumes ONTAP
          in AWS
        url: "/task-quick-deploy-aws.html"
      - title: Verwenden Sie die erweiterte Bereitstellungsmethode für Cloud Volumes
          ONTAP in AWS
        url: "/task-deploying-otc-aws.html"
      - title: Stellen Sie Cloud Volumes ONTAP in geheimen AWS-Regionen bereit
        url: "/task-getting-started-aws-c2s.html"
    - title: Erste Schritte in Microsoft Azure
      flavor: azure
      entries:
      - title: Informieren Sie sich über die Bereitstellungsoptionen von Cloud Volumes
          ONTAP in Azure
        url: "/concept-azure-mktplace-direct.html"
      - title: Erste Schritte in der NetApp Console
        entries:
        - title: Schnellstart
          url: "/task-getting-started-azure.html"
        - title: Planen Sie Ihre Konfiguration
          url: "/task-planning-your-config-azure.html"
        - title: Richten Sie Ihr Netzwerk ein
          url: "/reference-networking-azure.html"
        - title: Richten Sie die Verschlüsselung mit Ihrem Schlüssel ein
          url: "/task-set-up-azure-encryption.html"
        - title: Einrichten der Lizenzierung
          url: "/task-set-up-licensing-azure.html"
        - title: Aktivieren des Hochverfügbarkeitsmodus
          url: "/task-azure-high-availability-mode.html"
        - title: Aktivieren Sie VMOrchestratorZonalMultiFD für einzelne Verfügbarkeitszonen
          url: "/task-saz-feature.html"
        - title: Starten Sie Cloud Volumes ONTAP in Azure
          url: "/task-deploying-otc-azure.html"
        - title: Überprüfen des Azure-Plattformimages
          entries:
          - title: Überblick
            url: "/concept-azure-image-verification.html"
          - title: Herunterladen der Azure-Imagedatei
            url: "/task-azure-download-digest-file.html"
          - title: Exportieren der Azure-Imagedatei
            url: "/task-azure-image-export.html"
          - title: Dateisignatur überprüfen
            entries:
            - title: Erfahren Sie mehr über die Überprüfung von Dateisignaturen
              url: "/concept-azure-file-sig-verify.html"
            - title: Überprüfen der Dateisignatur unter Linux
              url: "/task-file-verification-linux.html"
            - title: Überprüfen der Dateisignatur unter macOS
              url: "/task-file-verification-mac.html"
      - title: Erste Schritte auf dem Marktplatz
        url: "/task-deploy-cvo-azure-mktplc.html"
    - title: Erste Schritte in Google Cloud
      flavor: gcp
      entries:
      - title: Schnellstart
        url: "/task-getting-started-gcp.html"
      - title: Planen Sie Ihre Konfiguration
        url: "/task-planning-your-config-gcp.html"
      - title: Richten Sie Ihr Netzwerk ein
        url: "/reference-networking-gcp.html"
      - title: Planen Sie VPC-Servicekontrollen
        url: "/reference-vpc-service-controls-gcp.html"
      - title: Erstellen eines Dienstkontos
        url: "/task-creating-gcp-service-account.html"
      - title: Verwenden Sie vom Kunden verwaltete Verschlüsselungsschlüssel
        url: "/task-setting-up-gcp-encryption.html"
      - title: Einrichten der Lizenzierung
        url: "/task-set-up-licensing-google.html"
      - title: Starten Sie Cloud Volumes ONTAP in Google Cloud
        url: "/task-deploying-gcp.html"
      - title: Google Cloud Platform-Bildüberprüfung
        entries:
        - title: Überblick
          url: "/concept-gcp-image-verification.html"
        - title: Konvertieren Sie das Bild auf GCP in das Raw-Format
          url: "/task-gcp-convert-image-raw.html"
        - title: Bildsignaturprüfung
          entries:
          - title: Überprüfen Sie die von GCP signierten Bilder
            url: "/concept-gcp-verify-signed-image.html"
          - title: Überprüfen Sie Inhalte mit OpenSSL
            url: "/task-verify-openssl-gcp.html"
  - title: Verwenden Sie Cloud Volumes ONTAP
    entries:
    - title: Lizenzverwaltung
      entries:
      - title: Kapazitätsbasierte Lizenzen verwalten
        url: "/task-manage-capacity-licenses.html"
      - title: Keystone -Abonnements verwalten
        url: "/task-manage-keystone.html"
      - title: Knotenbasierte Lizenzen verwalten
        url: "/task-manage-node-licenses.html"
    - title: Volume- und LUN-Verwaltung
      entries:
      - title: Erstellen von Volumes
        url: "/task-create-volumes.html"
      - title: Vorhandene Volumes verwalten
        url: "/task-manage-volumes.html"
      - title: Inaktive Daten werden in den Objektspeicher verschoben.
        url: "/task-tiering.html"
      - title: Verbinden einer LUN mit einem Host
        url: "/task-connect-lun.html"
      - title: Beschleunigen Sie den Datenzugriff mit FlexCache
        url: "/task-accelerate-data-access.html"
    - title: Aggregatverwaltung
      entries:
      - title: Erstellen von Aggregaten
        url: "/task-create-aggregates.html"
      - title: Vorhandene Aggregate verwalten
        url: "/task-manage-aggregates.html"
      - title: Verwalten der Kapazitätseinstellungen
        url: "/task-manage-capacity-settings.html"
    - title: Storage-VM-Verwaltung
      entries:
      - title: Arbeiten mit Speicher-VMs
        url: "/task-managing-svms.html"
      - title: Verwalten von Speicher-VMs in AWS
        flavor: aws
        url: "/task-managing-svms-aws.html"
      - title: Verwalten von Speicher-VMs in Azure
        flavor: azure
        url: "/task-managing-svms-azure.html"
      - title: Speicher-VMs in Google Cloud verwalten
        flavor: gcp
        url: "/task-managing-svms-gcp.html"
      - title: Einrichten der SVM-Notfallwiederherstellung
        url: "/task-manage-svm-dr.html"
    - title: Sicherheit und Datenverschlüsselung
      entries:
      - title: Verschlüsseln Sie Volumes mit NetApp -Verschlüsselung
        url: "/task-encrypting-volumes.html"
      - title: Schlüssel mit AWS Key Management Service verwalten
        flavor: aws
        url: "/task-aws-key-management.html"
      - title: Verwalten von Schlüsseln mit Azure Key Vault
        flavor: azure
        url: "/task-azure-key-vault.html"
      - title: Schlüssel mit Google Cloud KMS verwalten
        flavor: gcp
        url: "/task-google-key-manager.html"
      - title: Verbessern Sie den Ransomware-Schutz
        url: "/task-protecting-ransomware.html"
      - title: Erstellen Sie manipulationssichere Snapshot-Kopien für den WORM-Speicher
        url: "/reference-worm-snaplock.html"
    - title: Systemadministration
      entries:
      - title: Upgrade von Cloud Volumes ONTAP
        url: "/task-updating-ontap-cloud.html"
      - title: Registrieren Sie Pay-as-you-go-Systeme
        url: "/task-registering.html"
      - title: Konvertieren von knotenbasierten Lizenzen
        url: "/task-convert-node-capacity.html"
      - title: Stoppen und Starten eines Systems
        url: "/task-managing-state.html"
      - title: Systemzeit synchronisieren
        url: "/task-sync-time.html"
      - title: Ändern Sie die Schreibgeschwindigkeit des Systems
        url: "/task-modify-write-speed.html"
      - title: Ändern des Systemkennworts
        url: "/task-change-password.html"
      - title: Systeme hinzufügen, entfernen oder löschen
        entries:
        - title: Vorhandenes System hinzufügen
          url: "/task-adding-systems.html"
        - title: Entfernen eines Systems
          url: "/task-removing.html"
        - title: Löschen eines Systems
          url: "/task-deleting-system.html"
      - title: AWS -Verwaltung
        flavor: aws
        entries:
        - title: Arbeiten mit EC2-Instanzen in AWS
          url: "/task-change-ec2-instance.html"
        - title: Routentabellen für HA-Paare ändern
          url: "/task-change-route-tables.html"
        - title: Konfigurieren der Platzierungsgruppenerstellung
          url: task-configure-placement-group-failure-aws.html
      - title: Azure-Verwaltung
        flavor: azure
        entries:
        - title: Ändern des Azure-VM-Typs
          url: "/task-change-azure-vm.html"
        - title: CIFS-Sperren außer Kraft setzen
          url: "/task-overriding-cifs-locks.html"
        - title: Verwenden Sie einen Azure Private Link oder Dienstendpunkte
          url: "/task-enabling-private-link.html"
        - title: Ressourcengruppen verschieben
          url: "/task-moving-resource-groups-azure.html"
        - title: Trennen Sie den SnapMirror -Datenverkehr in Azure
          url: "/task-segregate-snapmirror-azure.html"
      - title: Google Cloud-Verwaltung
        flavor: gcp
        entries:
        - title: Ändern des Maschinentyps
          url: "/task-change-gcp-machine.html"
      - title: Verwaltung über den Systemmanager
        url: "/task-administer-advanced-view.html"
      - title: Verwaltung über die CLI
        url: "/task-connecting-to-otc.html"
    - title: Systemzustand und Ereignisse
      entries:
      - title: Überprüfen Sie das AutoSupport Setup
        url: "/task-verify-autosupport.html"
      - title: EMS konfigurieren
        url: "/task-configure-ems.html"
  - title: Konzepte
    entries:
    - title: Lizenzierung
      entries:
      - title: Lizenzierung in Cloud Volumes ONTAP
        url: "/concept-licensing.html"
      - title: Erfahren Sie mehr über kapazitätsbasierte Lizenzen
        url: "/concept-licensing-charging.html"
    - title: Storage
      entries:
      - title: Client-Protokolle
        url: "/concept-client-protocols.html"
      - title: Festplatten und Aggregate
        url: "/concept-storage.html"
      - title: Elastische Volumes in AWS
        flavor: aws
        url: "/concept-aws-elastic-volumes.html"
      - title: Daten-Tiering
        url: "/concept-data-tiering.html"
      - title: Speicherverwaltung
        url: "/concept-storage-management.html"
      - title: Schreibgeschwindigkeit
        url: "/concept-write-speed.html"
      - title: Flash-Cache
        url: "/concept-flash-cache.html"
      - title: WORM-Speicher
        url: "/concept-worm.html"
    - title: Hochverfügbarkeitspaare
      entries:
      - title: HA-Paare in AWS
        flavor: aws
        url: "/concept-ha.html"
      - title: HA-Paare in Azure
        flavor: azure
        url: "/concept-ha-azure.html"
      - title: HA-Paare in GCP
        flavor: gcp
        url: "/concept-ha-google-cloud.html"
      - title: Aktionen bei der Speicherübernahme
        url: "/concept-degraded-ha-pair.html"
    - title: Sicherheit
      url: "/concept-security.html"
    - title: Performance
      url: "/concept-performance.html"
    - title: Verwaltung von knotenbasiertem BYOL
      url: "/concept-license-management.html"
    - title: AutoSupport und Digital Advisor
      url: "/concept-active-iq.html"
    - title: Standardkonfigurationen
      url: "/reference-default-configs.html"
  - title: Wissen und Unterstützung
    entries:
    - title: Für Support registrieren
      url: "/task-support-registration.html"
    - title: Hilfe erhalten
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: Storage Management
  repo: storage-management-family
