---
sidebar: sidebar 
permalink: reference-versions.html 
keywords: versions, supported versions, new versions, cloud volumes ontap version 
summary: Mit der NetApp Console können Sie beim Erstellen eines neuen Cloud Volumes ONTAP Systems aus mehreren verschiedenen ONTAP Versionen auswählen. 
---
= Unterstützte ONTAP -Versionen für Cloud Volumes ONTAP Bereitstellungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die NetApp Console ermöglicht Ihnen die Auswahl aus mehreren verschiedenen ONTAP Versionen, wenn Sie ein Cloud Volumes ONTAP -System hinzufügen.

Cloud Volumes ONTAP-Versionen, die hier nicht aufgeführt sind, sind für neue Bereitstellungen nicht verfügbar. Die Patch- oder generische (General Availability) Version in einer hier aufgeführten Version stellt die Basisversion dar, die für die Bereitstellung verfügbar ist. Einzelheiten zu den verfügbaren Patches finden Sie in der  https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-new.html["versionierte Versionshinweise"^] für jede Version.

Informationen zum Upgrade finden Sie unter link:task-updating-ontap-cloud.html#supported-upgrade-paths["Unterstützte Upgradepfade"].

ifdef::aws[]



== AWS

Einzelner Knoten::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9,8
* 9.7 P5
* 9.5 P6


--
HA-Paar::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9,8
* 9.7 P5
* 9.5 P6


--


endif::aws[]

ifdef::azure[]



== Azurblau

Einzelner Knoten::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1 P3
* 9.15.1 P10
* 9.14.1 P13
* 9.13.1 P16
* 9.12.1 P18


--
HA-Paar::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1 P3
* 9.15.1 P10
* 9.14.1 P13
* 9.13.1 P16
* 9.12.1 P18


--


endif::azure[]

ifdef::gcp[]



== Google Cloud

Einzelner Knoten::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9,8
* 9.7 P5


--
HA-Paar::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9,8


--


endif::gcp[]
