---
sidebar: sidebar 
permalink: reference-default-configs.html 
keywords: svm, LIF, LIFs, configuration backups, attributes, autosize, security style, space guarantee, unix permissions, NTFS, UNIX, boot, root, disks, aggr0, aggr1, svm, svms, storage virtual machine, LIF failover, failover, attributes, volume attributes, boot disk, root disk, licenses, feature licenses, default licenses, ontap licenses, ontap features 
summary: Wenn Sie wissen, wie Cloud Volumes ONTAP standardmäßig konfiguriert ist, können Sie Ihre Systeme leichter einrichten und verwalten, insbesondere wenn Sie mit ONTAP vertraut sind, da sich die Standardkonfiguration für Cloud Volumes ONTAP von der von ONTAP unterscheidet. 
---
= Unterstützte Standardkonfigurationen für Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie wissen, wie Cloud Volumes ONTAP standardmäßig konfiguriert ist, können Sie Ihre Systeme leichter einrichten und verwalten, insbesondere wenn Sie mit ONTAP vertraut sind, da sich die Standardkonfiguration für Cloud Volumes ONTAP von der von ONTAP unterscheidet.



== Standard-Setup

* Die NetApp Console erstellt bei der Bereitstellung von Cloud Volumes ONTAP eine datenbereitstellende Speicher-VM.  Einige Konfigurationen unterstützen zusätzliche Speicher-VMs. link:task-managing-svms.html["Erfahren Sie mehr über die Verwaltung von Speicher-VMs"] .
+
Ab der Version 3.9.5 ist die logische Speicherplatzberichterstattung auf der ersten Speicher-VM aktiviert.  Wenn der Speicherplatz logisch gemeldet wird, meldet ONTAP den Volume-Speicherplatz so, dass der gesamte durch die Speichereffizienzfunktionen eingesparte physische Speicherplatz auch als verwendet gemeldet wird.  Informationen zu den Effizienzfunktionen für Inline-Speicher finden Sie im Knowledge Base-Artikel https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/What_Inline_Storage_Efficiency_features_are_supported_with_CVO#["KB: Welche Inline-Speichereffizienzfunktionen werden mit CVO unterstützt?"^]

* Die Konsole installiert automatisch die folgenden ONTAP Funktionslizenzen auf Cloud Volumes ONTAP:
+
** CIFS
** FlexCache
** FlexClone
** iSCSI
** Multi-Tenant Encryption Key Management (MTEKM), beginnend mit Cloud Volumes ONTAP 9.12.1 GA
** NetApp Volume Encryption (nur für Bring Your Own License (BYOL) oder registrierte Pay-as-you-go (PAYGO)-Systeme)
** NFS ifdef::aws[] endif::aws[] ifdef::azure[] endif::azure[]
** SnapMirror
** SnapRestore
** SnapVault


* Standardmäßig werden mehrere Netzwerkschnittstellen erstellt:
+
** Ein Cluster-Management-LIF
** Ein Cluster-übergreifendes LIF




ifdef::azure[]

* Ein SVM-Verwaltungs-LIF auf HA-Systemen in Azure


endif::azure[]

ifdef::gcp[]

* Ein SVM-Verwaltungs-LIF auf HA-Systemen in Google Cloud


endif::gcp[]

ifdef::aws[]

* Ein SVM-Management-LIF auf Einzelknotensystemen in AWS


endif::aws[]

* Ein Knotenverwaltungs-LIF


ifdef::gcp[]

+ In Google Cloud wird dieses LIF mit dem Intercluster-LIF kombiniert.

endif::gcp[]

* Ein iSCSI-Daten-LIF
* Ein CIFS- und NFS-Daten-LIF
+

NOTE: Aufgrund der Anforderungen des Cloud-Anbieters ist LIF-Failover für Cloud Volumes ONTAP standardmäßig deaktiviert.  Durch die Migration eines LIF auf einen anderen Port wird die externe Zuordnung zwischen IP-Adressen und Netzwerkschnittstellen auf der Instanz unterbrochen, wodurch der LIF nicht mehr zugänglich ist.

+
** Cloud Volumes ONTAP sendet Konfigurationssicherungen per HTTP an den Konsolenagenten.
+
Auf die Sicherungen kann über \http://ipaddress/occm/offboxconfig/ zugegriffen werden, wobei _ipaddress_ die IP-Adresse des Hosts des Konsolenagenten ist.

+
Sie können die Backups zur Neukonfiguration Ihres Cloud Volumes ONTAP Systems verwenden.  Weitere Informationen zu Konfigurationssicherungen finden Sie im https://docs.netapp.com/us-en/ontap/system-admin/config-backup-file-concept.html["ONTAP-Dokumentation"^] .

** Die Konsole legt einige Volume-Attribute anders fest als andere Verwaltungstools (z. B. ONTAP System Manager oder ONTAP CLI).
+
In der folgenden Tabelle sind die Volumeattribute aufgeführt, die von den Standardeinstellungen abweichen:

+
[cols="15,85"]
|===
| Attribut | Wert, den die Konsole konfiguriert 


| Autosize-Modus | wachsen 


| Maximale automatische Größe  a| 
1.000 Prozent


NOTE: Der Organisations- oder Kontoadministrator kann diesen Wert auf der Seite „Einstellungen“ ändern.



| Sicherheitsstil | NTFS für CIFS-Volumes UNIX für NFS-Volumes 


| Platzgarantie Stil | keiner 


| UNIX-Berechtigungen (nur NFS) | 777 
|===
+
Informationen zu diesen Attributen finden Sie unterlink:https://docs.netapp.com/us-en/ontap-cli-9121/volume-create.html["ONTAP _volume create_ Manpage"] .







== Interne Festplatten für Systemdaten

Zusätzlich zum Speicher für Benutzerdaten erwirbt die Konsole auch Cloud-Speicher für Systemdaten.

ifdef::aws[]



=== AWS

* Drei Festplatten pro Knoten für Boot-, Root- und Core-Daten:
+
** 47 GiB io1-Festplatte für Bootdaten
** 140 GiB GP3-Disk für Root-Daten
** 540 GiB GP2-Festplatte für Kerndaten


* Für HA-Paare:
+
** Zwei st1-EBS-Volumes für die Mediator-Instanz, eines mit ca. 8 GiB als Root-Disk und eines mit 4 GiB als Datendiskette
** Eine 140 GiB große gp3-Festplatte in jedem Knoten, die eine Kopie der Stammdaten des anderen Knotens enthält
+

NOTE: In einigen Zonen kann der verfügbare EBS-Festplattentyp nur gp2 sein.



* Ein EBS-Snapshot für jede Boot- und Root-Festplatte
+

NOTE: Beim Neustart werden automatisch Snapshots erstellt.

* Wenn Sie die Datenverschlüsselung in AWS mithilfe des Key Management Service (KMS) aktivieren, werden auch die Boot- und Root-Datenträger für Cloud Volumes ONTAP verschlüsselt.  Dazu gehört die Bootdiskette für die Mediatorinstanz in einem HA-Paar.  Die Festplatten werden mit dem CMK verschlüsselt, den Sie beim Hinzufügen eines Cloud Volumes ONTAP Systems auswählen.



TIP: In AWS befindet sich NVRAM auf der Startdiskette.

endif::aws[]

ifdef::azure[]



=== Azure (einzelner Knoten)

* Drei Premium-SSD-Festplatten:
+
** Eine 10-GiB-Festplatte für Startdaten
** Eine 140-GiB-Festplatte für Root-Daten
** Eine 512-GiB-Festplatte für NVRAM
+
Wenn die von Ihnen für Cloud Volumes ONTAP ausgewählte virtuelle Maschine Ultra-SSDs unterstützt, verwendet das System für NVRAM eine 32-GiB-Ultra-SSD anstelle einer Premium-SSD.



* Eine 1024 GiB Standard-HDD-Festplatte zum Speichern von Kernen
* Ein Azure-Snapshot für jede Startdiskette und jede Root-Diskette
* Jeder Datenträger in Azure wird standardmäßig im Ruhezustand verschlüsselt.
+
Wenn die virtuelle Maschine, die Sie für Cloud Volumes ONTAP ausgewählt haben, Premium SSD v2 Managed Disk als Datenträger unterstützt, verwendet das System eine 32 GiB Premium SSD v2 Managed Disk für NVRAM und eine weitere als Root-Datenträger.





=== Azure (HA-Paar)

.HA-Paare mit Seitenblob
* Zwei 10 GiB Premium SSD-Datenträger für das Startvolume (einer pro Knoten)
* Zwei 140 GiB Premium Storage-Seitenblobs für das Stammvolume (einer pro Knoten)
* Zwei 1024 GiB Standard-HDD-Festplatten zum Speichern von Kernen (eine pro Knoten)
* Zwei 512 GiB Premium SSD-Festplatten für NVRAM (eine pro Knoten)
* Ein Azure-Snapshot für jede Startdiskette und jede Root-Diskette
+

NOTE: Beim Neustart werden automatisch Snapshots erstellt.

* Jeder Datenträger in Azure wird standardmäßig im Ruhezustand verschlüsselt.


.HA-Paare mit gemeinsam genutzten verwalteten Datenträgern in mehreren Verfügbarkeitszonen
* Zwei 10 GiB Premium SSD-Datenträger für das Startvolume (einer pro Knoten)
* Zwei 512 GiB Premium SSD-Datenträger für das Stammvolume (einer pro Knoten)
* Zwei 1024 GiB Standard-HDD-Festplatten zum Speichern von Kernen (eine pro Knoten)
* Zwei 512 GiB Premium SSD-Festplatten für NVRAM (eine pro Knoten)
* Ein Azure-Snapshot für jede Startdiskette und jede Root-Diskette
+

NOTE: Beim Neustart werden automatisch Snapshots erstellt.

* Jeder Datenträger in Azure wird standardmäßig im Ruhezustand verschlüsselt.


.HA-Paare mit gemeinsam genutzten verwalteten Datenträgern in einzelnen Verfügbarkeitszonen
* Zwei 10 GiB Premium SSD-Datenträger für das Startvolume (einer pro Knoten)
* Zwei 512 GiB Premium SSD Shared Managed Disks für das Stammvolume (einer pro Knoten)
* Zwei 1024 GiB Standard-HDD-Festplatten zum Speichern von Kernen (eine pro Knoten)
* Zwei 512 GiB Premium SSD Managed Disks für NVRAM (eine pro Knoten)


Wenn Ihre virtuelle Maschine Premium SSD v2 Managed Disks als Datenträger unterstützt, verwendet sie 32 GiB Premium SSD v2 Managed Disks für NVRAM und 512 GiB Premium SSD v2 Shared Managed Disks für das Stammvolume.

Sie können HA-Paare in einer einzigen Verfügbarkeitszone bereitstellen und verwaltete SSD Premium v2-Datenträger verwenden, wenn die folgenden Bedingungen erfüllt sind:

* Die Version von Cloud Volumes ONTAP ist 9.15.1 oder höher.
* Die ausgewählte Region und Zone unterstützen Premium SSD v2 Managed Disks.  Informationen zu den unterstützten Regionen finden Sie unter https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/["Microsoft Azure-Website: Verfügbare Produkte nach Region"^] .
* Das Abonnement ist für Microsoft registriertlink:task-saz-feature.html["Microsoft.Compute/VMOrchestratorZonalMultiFD-Funktion"] .


endif::azure[]

ifdef::gcp[]



=== Google Cloud (einzelner Knoten)

* Eine persistente SSD-Festplatte mit 10 GiB für Startdaten
* Eine persistente 64-GiB-SSD-Festplatte für Root-Daten
* Eine persistente SSD-Festplatte mit 500 GiB für NVRAM
* Eine persistente Standardfestplatte mit 315 GiB zum Speichern von Kernen
* Snapshots für Boot- und Root-Daten
+

NOTE: Beim Neustart werden automatisch Snapshots erstellt.

* Boot- und Root-Disks sind standardmäßig verschlüsselt.




=== Google Cloud (HA-Paar)

* Zwei persistente 10-GiB-SSD-Festplatten für Startdaten
* Vier persistente 64-GiB-SSD-Festplatten für Root-Daten
* Zwei persistente SSD-Festplatten mit 500 GiB für NVRAM
* Zwei persistente Standard-Festplatten mit 315 GiB zum Speichern von Kernen
* Eine persistente 10-GiB-Standardfestplatte für Mediatordaten
* Eine persistente 10-GiB-Standardfestplatte für Mediator-Bootdaten
* Snapshots für Boot- und Root-Daten
+

NOTE: Beim Neustart werden automatisch Snapshots erstellt.

* Boot- und Root-Disks sind standardmäßig verschlüsselt.


endif::gcp[]



=== Wo sich die Festplatten befinden

Speicherlayout:

* Die Startdaten befinden sich auf einer Festplatte, die an die Instanz oder virtuelle Maschine angeschlossen ist.
+
Diese Festplatte, die das Boot-Image enthält, ist für Cloud Volumes ONTAP nicht verfügbar.

* Root-Daten, die die Systemkonfiguration und Protokolle enthalten, befinden sich in aggr0.
* Das Stammvolume der Storage Virtual Machine (SVM) befindet sich in aggr1.
* Datenvolumes befinden sich auch in aggr1.

