---
sidebar: sidebar 
permalink: reference-networking-azure.html 
keywords: networking, network, requirements, connection, connections, vnet, security group, security groups, subnet, vpn, internet, proxy, HTTP, private, proxy server, routing, firewall, autosupport, connection, jump host, outbound, ports, blob, service endpoint 
summary: Richten Sie Ihr Azure-Netzwerk so ein, dass Cloud Volumes ONTAP -Systeme ordnungsgemäß funktionieren können. 
---
= Einrichten des Azure-Netzwerks für Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die NetApp Konsole übernimmt die Einrichtung von Netzwerkkomponenten für Cloud Volumes ONTAP, wie z. B. IP-Adressen, Netzmasken und Routen.  Sie müssen sicherstellen, dass ausgehender Internetzugang verfügbar ist, dass genügend private IP-Adressen verfügbar sind, dass die richtigen Verbindungen vorhanden sind und mehr.



== Anforderungen für Cloud Volumes ONTAP

Die folgenden Netzwerkanforderungen müssen in Azure erfüllt sein.



=== Ausgehender Internetzugang

Cloud Volumes ONTAP -Systeme erfordern ausgehenden Internetzugang für den Zugriff auf externe Endpunkte für verschiedene Funktionen.  Cloud Volumes ONTAP kann nicht ordnungsgemäß funktionieren, wenn diese Endpunkte in Umgebungen mit strengen Sicherheitsanforderungen blockiert sind.

Der Konsolenagent kontaktiert außerdem mehrere Endpunkte für den täglichen Betrieb.  Informationen zu Endpunkten finden Sie unter https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html#step-3-set-up-networking["Vom Konsolenagenten kontaktierte Endpunkte anzeigen"^] Und https://docs.netapp.com/us-en/bluexp-setup-admin/reference-networking-saas-console.html["Vorbereiten des Netzwerks für die Verwendung der Konsole"^] .



==== Cloud Volumes ONTAP Endpunkte

Cloud Volumes ONTAP verwendet diese Endpunkte zur Kommunikation mit verschiedenen Diensten.

[cols="5*"]
|===
| Endpunkte | Gilt für | Zweck | Bereitstellungsmodi | Auswirkungen bei Nichtverfügbarkeit 


| \https://netapp-cloud-account.auth0.com | Authentifizierung  a| 
Wird zur Authentifizierung in der Konsole verwendet.
| Standard- und eingeschränkte Modi.  a| 
Die Benutzerauthentifizierung schlägt fehl und die folgenden Dienste sind weiterhin nicht verfügbar:

* Cloud Volumes ONTAP Dienste
* ONTAP -Dienste
* Protokolle und Proxy-Dienste




| https://vault.azure.net[] | Schlüsseltresor | Wird verwendet, um geheime Clientschlüssel aus dem Azure Key Vault abzurufen, wenn vom Kunden verwaltete Schlüssel (CMK) verwendet werden. | Standard-, eingeschränkter und privater Modus. | Cloud Volumes ONTAP Dienste sind nicht verfügbar. 


| \https://api.bluexp.netapp.com/tenancy | Mietverhältnis | Wird verwendet, um die Cloud Volumes ONTAP -Ressourcen von der Konsole abzurufen, um Ressourcen und Benutzer zu autorisieren. | Standard- und eingeschränkte Modi. | Cloud Volumes ONTAP Ressourcen und die Benutzer sind nicht autorisiert. 


| \https://mysupport.netapp.com/aods/asupmessage \https://mysupport.netapp.com/asupprod/post/1.0/postAsup | AutoSupport | Wird verwendet, um AutoSupport Telemetriedaten an den NetApp Support zu senden. | Standard- und eingeschränkte Modi. | AutoSupport -Informationen bleiben unversehrt. 


| \https://management.azure.com \https://login.microsoftonline.com \https://bluexpinfraprod.eastus2.data.azurecr.io \https://core.windows.net | Öffentliche Regionen | Kommunikation mit Azure-Diensten. | Standard-, eingeschränkter und privater Modus. | Cloud Volumes ONTAP kann nicht mit dem Azure-Dienst kommunizieren, um bestimmte Vorgänge für die Konsole in Azure auszuführen. 


| \https://management.chinacloudapi.cn \https://login.chinacloudapi.cn \https://blob.core.chinacloudapi.cn \https://core.chinacloudapi.cn | Region China | Kommunikation mit Azure-Diensten. | Standard-, eingeschränkter und privater Modus. | Cloud Volumes ONTAP kann nicht mit dem Azure-Dienst kommunizieren, um bestimmte Vorgänge für die Konsole in Azure auszuführen. 


| \https://management.microsoftazure.de \https://login.microsoftonline.de \https://blob.core.cloudapi.de \https://core.cloudapi.de | Deutschland Region | Kommunikation mit Azure-Diensten. | Standard-, eingeschränkter und privater Modus. | Cloud Volumes ONTAP kann nicht mit dem Azure-Dienst kommunizieren, um bestimmte Vorgänge für die Konsole in Azure auszuführen. 


| \https://management.usgovcloudapi.net \https://login.microsoftonline.us \https://blob.core.usgovcloudapi.net \https://core.usgovcloudapi.net | Regierungsregionen | Kommunikation mit Azure-Diensten. | Standard-, eingeschränkter und privater Modus. | Cloud Volumes ONTAP kann nicht mit dem Azure-Dienst kommunizieren, um bestimmte Vorgänge für die Konsole in Azure auszuführen. 


| \https://management.azure.microsoft.scloud \https://login.microsoftonline.microsoft.scloud \https://blob.core.microsoft.scloud \https://core.microsoft.scloud | Regierungsregionen des Verteidigungsministeriums | Kommunikation mit Azure-Diensten. | Standard-, eingeschränkter und privater Modus. | Cloud Volumes ONTAP kann nicht mit dem Azure-Dienst kommunizieren, um bestimmte Vorgänge für die Konsole in Azure auszuführen. 
|===


=== Netzwerkproxykonfiguration des NetApp Console-Agenten

Sie können die Proxyserverkonfiguration des NetApp Console-Agenten verwenden, um ausgehenden Internetzugriff von Cloud Volumes ONTAP zu aktivieren.  Die Konsole unterstützt zwei Arten von Proxys:

* *Expliziter Proxy*: Der ausgehende Datenverkehr von Cloud Volumes ONTAP verwendet die HTTP-Adresse des Proxyservers, der während der Proxykonfiguration des Konsolenagenten angegeben wurde.  Der Administrator hat möglicherweise auch Benutzeranmeldeinformationen und Stammzertifizierungsstellenzertifikate für eine zusätzliche Authentifizierung konfiguriert.  Wenn ein Stamm-CA-Zertifikat für den expliziten Proxy verfügbar ist, stellen Sie sicher , dass Sie dasselbe Zertifikat erhalten und mithilfe des https://docs.netapp.com/us-en/ontap-cli/security-certificate-install.html["ONTAP CLI: Sicherheitszertifikat installieren"^] Befehl.
* *Transparenter Proxy*: Das Netzwerk ist so konfiguriert, dass ausgehender Datenverkehr von Cloud Volumes ONTAP automatisch über den Proxy für den Konsolenagenten geleitet wird.  Beim Einrichten eines transparenten Proxys muss der Administrator für die Konnektivität von Cloud Volumes ONTAP nur ein Stamm-CA-Zertifikat bereitstellen, nicht die HTTP-Adresse des Proxyservers.  Stellen Sie sicher, dass Sie dasselbe Stamm-CA-Zertifikat erhalten und auf Ihr Cloud Volumes ONTAP System hochladen, indem Sie das https://docs.netapp.com/us-en/ontap-cli/security-certificate-install.html["ONTAP CLI: Sicherheitszertifikat installieren"^] Befehl.


Informationen zum Konfigurieren von Proxy-Servern finden Sie im https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["Konfigurieren des Konsolenagenten zur Verwendung eines Proxyservers"^] .



=== IP-Adressen

Die Konsole weist Cloud Volumes ONTAP in Azure automatisch die erforderliche Anzahl privater IP-Adressen zu.  Sie müssen sicherstellen, dass in Ihrem Netzwerk genügend private IP-Adressen verfügbar sind.

Die Anzahl der für Cloud Volumes ONTAP zugewiesenen LIFs hängt davon ab, ob Sie ein Einzelknotensystem oder ein HA-Paar bereitstellen.  Ein LIF ist eine IP-Adresse, die einem physischen Port zugeordnet ist.  Für Verwaltungstools wie SnapCenter ist ein SVM-Verwaltungs-LIF erforderlich.


NOTE: Ein iSCSI-LIF bietet Clientzugriff über das iSCSI-Protokoll und wird vom System für andere wichtige Netzwerk-Workflows verwendet.  Diese LIFs sind erforderlich und sollten nicht gelöscht werden.



==== IP-Adressen für ein Einzelknotensystem

Die Konsole weist einem Einzelknotensystem 5 oder 6 IP-Adressen zu:

* Cluster-Verwaltungs-IP
* Knotenverwaltungs-IP
* Intercluster-IP für SnapMirror
* NFS/CIFS-IP
* iSCSI-IP
+

NOTE: Die iSCSI-IP bietet Clientzugriff über das iSCSI-Protokoll.  Es wird vom System auch für andere wichtige Netzwerk-Workflows verwendet.  Dieses LIF ist erforderlich und sollte nicht gelöscht werden.

* SVM-Verwaltung (optional – nicht standardmäßig konfiguriert)




==== IP-Adressen für HA-Paare

Die Konsole weist während der Bereitstellung 4 NICs (pro Knoten) IP-Adressen zu.

Beachten Sie, dass die Konsole ein SVM-Verwaltungs-LIF auf HA-Paaren erstellt, jedoch nicht auf Einzelknotensystemen in Azure.

*NIC0*

* Knotenverwaltungs-IP
* Intercluster-IP
* iSCSI-IP
+

NOTE: Die iSCSI-IP bietet Clientzugriff über das iSCSI-Protokoll.  Es wird vom System auch für andere wichtige Netzwerk-Workflows verwendet.  Dieses LIF ist erforderlich und sollte nicht gelöscht werden.



*NIC1*

* Cluster-Netzwerk-IP


*NIC2*

* Cluster-Interconnect-IP (HA IC)


*NIC3*

* Pageblob NIC-IP (Festplattenzugriff)



NOTE: NIC3 ist nur auf HA-Bereitstellungen anwendbar, die Page-Blob-Speicher verwenden.

Die oben genannten IP-Adressen werden bei Failover-Ereignissen nicht migriert.

Darüber hinaus sind 4 Frontend-IPs (FIPs) für die Migration bei Failover-Ereignissen konfiguriert.  Diese Frontend-IPs befinden sich im Load Balancer.

* Cluster-Verwaltungs-IP
* NodeA-Daten-IP (NFS/CIFS)
* NodeB-Daten-IP (NFS/CIFS)
* SVM-Verwaltungs-IP




=== Sichere Verbindungen zu Azure-Diensten

Standardmäßig aktiviert die Konsole einen Azure Private Link für Verbindungen zwischen Cloud Volumes ONTAP und Azure Page Blob Storage-Konten.

In den meisten Fällen müssen Sie nichts tun – die Konsole verwaltet den Azure Private Link für Sie.  Wenn Sie jedoch Azure Private DNS verwenden, müssen Sie eine Konfigurationsdatei bearbeiten.  Sie sollten sich auch über eine Anforderung hinsichtlich des Speicherorts des Konsolen-Agenten in Azure im Klaren sein.

Sie können die Private Link-Verbindung auch deaktivieren, wenn dies für Ihre Geschäftsanforderungen erforderlich ist.  Wenn Sie die Verknüpfung deaktivieren, konfiguriert die Konsole Cloud Volumes ONTAP so, dass stattdessen ein Service-Endpunkt verwendet wird.

link:task-enabling-private-link.html["Erfahren Sie mehr über die Verwendung von Azure Private Links oder Service-Endpunkten mit Cloud Volumes ONTAP"] .



=== Verbindungen zu anderen ONTAP -Systemen

Um Daten zwischen einem Cloud Volumes ONTAP -System in Azure und ONTAP -Systemen in anderen Netzwerken zu replizieren, benötigen Sie eine VPN-Verbindung zwischen dem Azure VNet und dem anderen Netzwerk, beispielsweise Ihrem Unternehmensnetzwerk.

Anweisungen hierzu finden Sie im https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-howto-site-to-site-resource-manager-portal["Microsoft Azure-Dokumentation: Erstellen einer Site-to-Site-Verbindung im Azure-Portal"^] .



=== Port für die HA-Verbindung

Ein Cloud Volumes ONTAP HA-Paar umfasst eine HA-Verbindung, die es jedem Knoten ermöglicht, kontinuierlich zu prüfen, ob sein Partner funktioniert, und Protokolldaten für den nichtflüchtigen Speicher des anderen zu spiegeln.  Die HA-Verbindung verwendet den TCP-Port 10006 für die Kommunikation.

Standardmäßig ist die Kommunikation zwischen den HA-Interconnect-LIFs offen und es gibt keine Sicherheitsgruppenregeln für diesen Port.  Wenn Sie jedoch eine Firewall zwischen den HA-Interconnect-LIFs erstellen, müssen Sie sicherstellen, dass der TCP-Verkehr für Port 10006 geöffnet ist, damit das HA-Paar ordnungsgemäß funktionieren kann.



=== Nur ein HA-Paar in einer Azure-Ressourcengruppe

Sie müssen für jedes Cloud Volumes ONTAP HA-Paar, das Sie in Azure bereitstellen, eine _dedizierte_ Ressourcengruppe verwenden.  In einer Ressourcengruppe wird nur ein HA-Paar unterstützt.

Bei der Konsole treten Verbindungsprobleme auf, wenn Sie versuchen, ein zweites Cloud Volumes ONTAP HA-Paar in einer Azure-Ressourcengruppe bereitzustellen.



=== Sicherheitsgruppenregeln

Die Konsole erstellt Azure-Sicherheitsgruppen, die die eingehenden und ausgehenden Regeln für den erfolgreichen Betrieb von Cloud Volumes ONTAP enthalten. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-ports-azure.html["Sicherheitsgruppenregeln für den Konsolenagenten anzeigen"^] .

Die Azure-Sicherheitsgruppen für Cloud Volumes ONTAP erfordern, dass die entsprechenden Ports für die interne Kommunikation zwischen den Knoten geöffnet sind. https://docs.netapp.com/us-en/ontap/networking/ontap_internal_ports.html["Erfahren Sie mehr über die internen Ports von ONTAP"^] .

Wir empfehlen nicht, die vordefinierten Sicherheitsgruppen zu ändern oder benutzerdefinierte Sicherheitsgruppen zu verwenden.  Wenn Sie dies jedoch tun müssen, beachten Sie, dass für den Bereitstellungsprozess das Cloud Volumes ONTAP -System vollständigen Zugriff innerhalb seines eigenen Subnetzes benötigt.  Wenn Sie nach Abschluss der Bereitstellung die Netzwerksicherheitsgruppe ändern möchten, achten Sie darauf, dass die Cluster-Ports und HA-Netzwerk-Ports geöffnet bleiben.  Dies gewährleistet eine nahtlose Kommunikation innerhalb des Cloud Volumes ONTAP Clusters (Any-to-Any-Kommunikation zwischen den Knoten).



==== Eingehende Regeln für Einzelknotensysteme

Wenn Sie ein Cloud Volumes ONTAP -System hinzufügen und eine vordefinierte Sicherheitsgruppe auswählen, können Sie den Datenverkehr innerhalb einer der folgenden Gruppen zulassen:

* *Nur ausgewähltes VNet*: Die Quelle für eingehenden Datenverkehr ist der Subnetzbereich des VNet für das Cloud Volumes ONTAP -System und der Subnetzbereich des VNet, in dem sich der Konsolenagent befindet.  Dies ist die empfohlene Option.
* *Alle VNets*: Die Quelle für eingehenden Datenverkehr ist der IP-Bereich 0.0.0.0/0.
* *Deaktiviert*: Diese Option schränkt den öffentlichen Netzwerkzugriff auf Ihr Speicherkonto ein und deaktiviert die Datenschichtung für Cloud Volumes ONTAP -Systeme.  Dies ist eine empfohlene Option, wenn Ihre privaten IP-Adressen aufgrund von Sicherheitsbestimmungen und -richtlinien nicht einmal innerhalb desselben VNet offengelegt werden sollen.


[cols="4*"]
|===
| Priorität und Name | Port und Protokoll | Quelle und Ziel | Beschreibung 


| 1000 eingehendes SSH | 22 TCP | Beliebig zu Beliebig | SSH-Zugriff auf die IP-Adresse des Cluster-Management-LIF oder eines Node-Management-LIF 


| 1001 eingehendes_http | 80 TCP | Beliebig zu Beliebig | HTTP-Zugriff auf die ONTAP System Manager-Webkonsole über die IP-Adresse des Cluster-Management-LIF 


| 1002 inbound_111_tcp | 111 TCP | Beliebig zu Beliebig | Remote Procedure Call für NFS 


| 1003 inbound_111_udp | 111 UDP | Beliebig zu Beliebig | Remote Procedure Call für NFS 


| 1004 inbound_139 | 139 TCP | Beliebig zu Beliebig | NetBIOS-Dienstsitzung für CIFS 


| 1005 inbound_161-162 _tcp | 161-162 TCP | Beliebig zu Beliebig | Einfaches Netzwerkverwaltungsprotokoll 


| 1006 inbound_161-162 _udp | 161-162 UDP | Beliebig zu Beliebig | Einfaches Netzwerkverwaltungsprotokoll 


| 1007 inbound_443 | 443 TCP | Beliebig zu Beliebig | Konnektivität mit dem Konsolenagenten und HTTPS-Zugriff auf die ONTAP System Manager-Webkonsole unter Verwendung der IP-Adresse des Cluster-Management-LIF 


| 1008 inbound_445 | 445 TCP | Beliebig zu Beliebig | Microsoft SMB/CIFS über TCP mit NetBIOS-Framing 


| 1009 inbound_635_tcp | 635 TCP | Beliebig zu Beliebig | NFS-Mount 


| 1010 inbound_635_udp | 635 UDP | Beliebig zu Beliebig | NFS-Mount 


| 1011 inbound_749 | 749 TCP | Beliebig zu Beliebig | Kerberos 


| 1012 inbound_2049_tcp | 2049 TCP | Beliebig zu Beliebig | NFS-Server-Daemon 


| 1013 inbound_2049_udp | 2049 UDP | Beliebig zu Beliebig | NFS-Server-Daemon 


| 1014 inbound_3260 | 3260 TCP | Beliebig zu Beliebig | iSCSI-Zugriff über das iSCSI-Daten-LIF 


| 1015 inbound_4045-4046_tcp | 4045-4046 TCP | Beliebig zu Beliebig | NFS-Sperrdaemon und Netzwerkstatusmonitor 


| 1016 inbound_4045-4046_udp | 4045-4046 UDP | Beliebig zu Beliebig | NFS-Sperrdaemon und Netzwerkstatusmonitor 


| 1017 eingehend_10000 | 10000 TCP | Beliebig zu Beliebig | Sicherung mit NDMP 


| 1018 eingehend_11104-11105 | 11104-11105 TCP | Beliebig zu Beliebig | SnapMirror -Datenübertragung 


| 3000 inbound_deny _all_tcp | Beliebiger TCP-Port | Beliebig zu Beliebig | Blockieren Sie den gesamten anderen eingehenden TCP-Verkehr 


| 3001 inbound_deny _all_udp | Beliebiger Port UDP | Beliebig zu Beliebig | Blockieren Sie den gesamten anderen eingehenden UDP-Verkehr 


| 65000 AllowVnetInBound | Beliebiger Port, jedes Protokoll | VirtualNetwork zu VirtualNetwork | Eingehender Datenverkehr aus dem VNet 


| 65001 AllowAzureLoad BalancerInBound | Beliebiger Port, jedes Protokoll | AzureLoadBalancer zu Any | Datenverkehr vom Azure Standard Load Balancer 


| 65500 DenyAllInBound | Beliebiger Port, jedes Protokoll | Beliebig zu Beliebig | Blockieren Sie den gesamten anderen eingehenden Datenverkehr 
|===


==== Eingehende Regeln für HA-Systeme

Wenn Sie ein Cloud Volumes ONTAP -System hinzufügen und eine vordefinierte Sicherheitsgruppe auswählen, können Sie den Datenverkehr innerhalb einer der folgenden Gruppen zulassen:

* *Nur ausgewähltes VNet*: Die Quelle für eingehenden Datenverkehr ist der Subnetzbereich des VNet für das Cloud Volumes ONTAP -System und der Subnetzbereich des VNet, in dem sich der Konsolenagent befindet.  Dies ist die empfohlene Option.
* *Alle VNets*: Die Quelle für eingehenden Datenverkehr ist der IP-Bereich 0.0.0.0/0.



NOTE: HA-Systeme unterliegen weniger Eingangsregeln als Einzelknotensysteme, da der eingehende Datenverkehr über den Azure Standard Load Balancer läuft.  Aus diesem Grund sollte der Datenverkehr vom Load Balancer geöffnet sein, wie in der Regel „AllowAzureLoadBalancerInBound“ gezeigt.

* *Deaktiviert*: Diese Option schränkt den öffentlichen Netzwerkzugriff auf Ihr Speicherkonto ein und deaktiviert die Datenschichtung für Cloud Volumes ONTAP -Systeme.  Dies ist eine empfohlene Option, wenn Ihre privaten IP-Adressen aufgrund von Sicherheitsbestimmungen und -richtlinien nicht einmal innerhalb desselben VNet offengelegt werden sollen.


[cols="4*"]
|===
| Priorität und Name | Port und Protokoll | Quelle und Ziel | Beschreibung 


| 100 inbound_443 | 443 Jedes Protokoll | Beliebig zu Beliebig | Konnektivität mit dem Konsolenagenten und HTTPS-Zugriff auf die ONTAP System Manager-Webkonsole unter Verwendung der IP-Adresse des Cluster-Management-LIF 


| 101 inbound_111_tcp | 111 Jedes Protokoll | Beliebig zu Beliebig | Remote Procedure Call für NFS 


| 102 inbound_2049_tcp | 2049 Jedes Protokoll | Beliebig zu Beliebig | NFS-Server-Daemon 


| 111 eingehendes_ssh | 22 Jedes Protokoll | Beliebig zu Beliebig | SSH-Zugriff auf die IP-Adresse des Cluster-Management-LIF oder eines Node-Management-LIF 


| 121 inbound_53 | 53 Jedes Protokoll | Beliebig zu Beliebig | DNS und CIFS 


| 65000 AllowVnetInBound | Beliebiger Port, jedes Protokoll | VirtualNetwork zu VirtualNetwork | Eingehender Datenverkehr aus dem VNet 


| 65001 AllowAzureLoad BalancerInBound | Beliebiger Port, jedes Protokoll | AzureLoadBalancer zu Any | Datenverkehr vom Azure Standard Load Balancer 


| 65500 DenyAllInBound | Beliebiger Port, jedes Protokoll | Beliebig zu Beliebig | Blockieren Sie den gesamten anderen eingehenden Datenverkehr 
|===


==== Ausgangsregeln

Die vordefinierte Sicherheitsgruppe für Cloud Volumes ONTAP öffnet den gesamten ausgehenden Datenverkehr. Wenn das akzeptabel ist, befolgen Sie die grundlegenden Regeln für ausgehende Nachrichten. Wenn Sie strengere Regeln benötigen, verwenden Sie die erweiterten Ausgangsregeln.



===== Grundlegende Ausgangsregeln

Die vordefinierte Sicherheitsgruppe für Cloud Volumes ONTAP umfasst die folgenden ausgehenden Regeln.

[cols="3*"]
|===
| Hafen | Protokoll | Zweck 


| Alle | Alle TCP | Der gesamte ausgehende Verkehr 


| Alle | Alle UDP | Der gesamte ausgehende Verkehr 
|===


===== Erweiterte Ausgangsregeln

Wenn Sie strenge Regeln für ausgehenden Datenverkehr benötigen, können Sie die folgenden Informationen verwenden, um nur die Ports zu öffnen, die für die ausgehende Kommunikation von Cloud Volumes ONTAP erforderlich sind.


NOTE: Die Quelle ist die Schnittstelle (IP-Adresse) auf dem Cloud Volumes ONTAP -System.

[cols="10,10,6,20,20,34"]
|===
| Service | Hafen | Protokoll | Quelle | Ziel | Zweck 


.18+| Active Directory | 88 | TCP | Knotenverwaltung LIF | Active Directory-Gesamtstruktur | Kerberos V-Authentifizierung 


| 137 | UDP | Knotenverwaltung LIF | Active Directory-Gesamtstruktur | NetBIOS-Namensdienst 


| 138 | UDP | Knotenverwaltung LIF | Active Directory-Gesamtstruktur | NetBIOS-Datagrammdienst 


| 139 | TCP | Knotenverwaltung LIF | Active Directory-Gesamtstruktur | NetBIOS-Dienstsitzung 


| 389 | TCP und UDP | Knotenverwaltung LIF | Active Directory-Gesamtstruktur | LDAP 


| 445 | TCP | Knotenverwaltung LIF | Active Directory-Gesamtstruktur | Microsoft SMB/CIFS über TCP mit NetBIOS-Framing 


| 464 | TCP | Knotenverwaltung LIF | Active Directory-Gesamtstruktur | Kerberos V Passwort ändern & festlegen (SET_CHANGE) 


| 464 | UDP | Knotenverwaltung LIF | Active Directory-Gesamtstruktur | Kerberos-Schlüsselverwaltung 


| 749 | TCP | Knotenverwaltung LIF | Active Directory-Gesamtstruktur | Kerberos V Passwort ändern und festlegen (RPCSEC_GSS) 


| 88 | TCP | Daten-LIF (NFS, CIFS, iSCSI) | Active Directory-Gesamtstruktur | Kerberos V-Authentifizierung 


| 137 | UDP | Daten-LIF (NFS, CIFS) | Active Directory-Gesamtstruktur | NetBIOS-Namensdienst 


| 138 | UDP | Daten-LIF (NFS, CIFS) | Active Directory-Gesamtstruktur | NetBIOS-Datagrammdienst 


| 139 | TCP | Daten-LIF (NFS, CIFS) | Active Directory-Gesamtstruktur | NetBIOS-Dienstsitzung 


| 389 | TCP und UDP | Daten-LIF (NFS, CIFS) | Active Directory-Gesamtstruktur | LDAP 


| 445 | TCP | Daten-LIF (NFS, CIFS) | Active Directory-Gesamtstruktur | Microsoft SMB/CIFS über TCP mit NetBIOS-Framing 


| 464 | TCP | Daten-LIF (NFS, CIFS) | Active Directory-Gesamtstruktur | Kerberos V Passwort ändern & festlegen (SET_CHANGE) 


| 464 | UDP | Daten-LIF (NFS, CIFS) | Active Directory-Gesamtstruktur | Kerberos-Schlüsselverwaltung 


| 749 | TCP | Daten-LIF (NFS, CIFS) | Active Directory-Gesamtstruktur | Kerberos V Passwort ändern & festlegen (RPCSEC_GSS) 


.3+| AutoSupport | HTTPS | 443 | Knotenverwaltung LIF | mysupport.netapp.com | AutoSupport (HTTPS ist die Standardeinstellung) 


| HTTP | 80 | Knotenverwaltung LIF | mysupport.netapp.com | AutoSupport (nur wenn das Transportprotokoll von HTTPS auf HTTP geändert wird) 


| TCP | 3128 | Knotenverwaltung LIF | Konsolenagent | Senden von AutoSupport -Nachrichten über einen Proxyserver auf dem Konsolenagenten, wenn keine ausgehende Internetverbindung verfügbar ist 


| Konfigurationssicherungen | HTTP | 80 | Knotenverwaltung LIF | \http://<IP-Adresse des Konsolenagenten>/occm/offboxconfig | Senden Sie Konfigurationssicherungen an den Konsolenagenten. link:https://docs.netapp.com/us-en/ontap/system-admin/node-cluster-config-backed-up-automatically-concept.html["ONTAP-Dokumentation"^] . 


| DHCP | 68 | UDP | Knotenverwaltung LIF | DHCP | DHCP-Client für die Ersteinrichtung 


| DHCPS | 67 | UDP | Knotenverwaltung LIF | DHCP | DHCP-Server 


| DNS | 53 | UDP | Knotenverwaltungs-LIF und Daten-LIF (NFS, CIFS) | DNS | DNS 


| NDMP | 18600–18699 | TCP | Knotenverwaltung LIF | Zielserver | NDMP-Kopie 


| SMTP | 25 | TCP | Knotenverwaltung LIF | Mailserver | SMTP-Benachrichtigungen, können für AutoSupport verwendet werden 


.4+| SNMP | 161 | TCP | Knotenverwaltung LIF | Monitorserver | Überwachung durch SNMP-Traps 


| 161 | UDP | Knotenverwaltung LIF | Monitorserver | Überwachung durch SNMP-Traps 


| 162 | TCP | Knotenverwaltung LIF | Monitorserver | Überwachung durch SNMP-Traps 


| 162 | UDP | Knotenverwaltung LIF | Monitorserver | Überwachung durch SNMP-Traps 


.2+| SnapMirror | 11104 | TCP | Intercluster LIF | ONTAP Intercluster-LIFs | Verwaltung von Intercluster-Kommunikationssitzungen für SnapMirror 


| 11105 | TCP | Intercluster LIF | ONTAP Intercluster-LIFs | SnapMirror -Datenübertragung 


| Syslog | 514 | UDP | Knotenverwaltung LIF | Syslog-Server | Syslog-Weiterleitungsnachrichten 
|===


== Anforderungen für den Konsolenagenten

Wenn Sie noch keinen Konsolenagenten erstellt haben, sollten Sie auch die Netzwerkanforderungen für den Konsolenagenten überprüfen.

* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-azure.html["Netzwerkanforderungen für den Konsolenagenten anzeigen"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-ports-azure.html["Sicherheitsgruppenregeln in Azure"^]


.Verwandte Themen
* link:task-verify-autosupport.html["Überprüfen Sie das AutoSupport -Setup für Cloud Volumes ONTAP"]
* https://docs.netapp.com/us-en/ontap/networking/ontap_internal_ports.html["Erfahren Sie mehr über die internen Ports von ONTAP"^] .

