---
sidebar: sidebar 
permalink: task-encrypting-volumes.html 
keywords: encrypt, encryption, data, volumes, netapp volume encryption, volume encryption, nve, key managers, kmip, key management servers, license, ssl certificates, nae, netapp aggregate encryption 
summary: 'Cloud Volumes ONTAP unterstützt sowohl NetApp Volume Encryption (NVE) als auch NetApp Aggregate Encryption (NAE) mit einem externen Schlüsselmanager.  NVE und NAE sind standardmäßig aktiviert, wenn Sie einen externen Schlüsselmanager einrichten.' 
---
= Verschlüsseln Sie Volumes auf Cloud Volumes ONTAP mit NetApp -Verschlüsselungslösungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP unterstützt NetApp Volume Encryption (NVE) und NetApp Aggregate Encryption (NAE).  NVE und NAE sind softwarebasierte Lösungen, die eine FIPS 140-2-konforme Data-at-Rest-Verschlüsselung von Volumes ermöglichen. link:concept-security.html["Erfahren Sie mehr über diese Verschlüsselungslösungen"] .

Sowohl NVE als auch NAE werden mit einem externen Schlüsselmanager unterstützt.

Wenn Sie NVE verwenden, haben Sie die Möglichkeit, den Schlüsseltresor Ihres Cloud-Anbieters zum Schutz der ONTAP Verschlüsselungsschlüssel zu verwenden:

* AWS Key Management Service (ab 9.12.0)
* Azure-Schlüsseltresor (AKV)
* Google Cloud-Schlüsselverwaltungsdienst


Neue Aggregate verfügen nach der Einrichtung eines externen Schlüsselmanagers standardmäßig über aktiviertes NAE. Neue Volumes, die nicht Teil eines NAE-Aggregats sind, verfügen standardmäßig über aktiviertes NVE (z. B. wenn bereits Aggregate vorhanden sind, die vor der Einrichtung eines externen Schlüsselmanagers erstellt wurden).

Cloud Volumes ONTAP unterstützt keine integrierte Schlüsselverwaltung.

.Bevor Sie beginnen
Ihr Cloud Volumes ONTAP System sollte beim NetApp Support registriert sein. Eine Lizenz für NetApp Volume Encryption wird automatisch auf jedem Cloud Volumes ONTAP System installiert, das beim NetApp Support registriert ist.

* https://docs.netapp.com/us-en/console-setup-admin/task-adding-nss-accounts.html["Hinzufügen von NetApp Support Site Konten zur Konsole"^]
* link:task-registering.html["Registrieren Sie Pay-as-you-go-Systeme"]



NOTE: Die NetApp Console installiert die NVE-Lizenz nicht auf Systemen, die sich in der Region China befinden.

.Schritte
. Die Liste der unterstützten Schlüsselmanager finden Sie in der  http://mysupport.netapp.com/matrix["NetApp Interoperabilitätsmatrix-Tool"^].
+

TIP: Nach der Lösung *Key Managers* kann gesucht werden.

. link:task-connecting-to-otc.html["Herstellen einer Verbindung zur Cloud Volumes ONTAP CLI"^].
. Externe Schlüsselverwaltung konfigurieren.
+
** AWS: link:task-aws-key-management.html["AWS-Schlüsselverwaltungsdienst"]
** Azure: link:task-azure-key-vault.html["Azure-Schlüsseltresor (AKV)"]
** Google Cloud: link:task-google-key-manager.html["Google Cloud-Schlüsselverwaltungsdienst"]



