---
sidebar: sidebar 
permalink: task-getting-started-aws.html 
keywords: amazon web services, aws, netapp, data fabric, hybrid cloud, cloud, public cloud, networking, vpc, quick, getting started, install, installing, deploy, deploying, setup, setting up, launching, requirements, prerequisites, cloud central, get started, network, vpn, multi-cloud, tier, storage tier, data tier, vpc endpoint, endpoint, S3, subscribe, subscribing, marketplace, granting, permissions, policy, iam policy, ec2 console, ami, mediator, connectivity, internet, outbound, endpoint, connection, networks, replicating, ec2 service, policies, attach, iam user, access key, secret key, keys, sign up, cloud manager, cloud volumes ontap, cloud ontap, create, console 
summary: Es sollte überprüft werden, ob die Voraussetzungen für die Bereitstellung von Cloud Volumes ONTAP in AWS erfüllt sind. 
---
= Bereitstellungsübersicht für Cloud Volumes ONTAP in AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Für die Bereitstellung von Cloud Volumes ONTAP benötigen Sie zunächst Informationen zu Ihrem AWS-Abonnement und zu Cloud Volumes ONTAP-Lizenzen. Es muss außerdem überprüft werden, ob ein NetApp Console-Agent für Ihr AWS-Konto erstellt wurde. Viele der in diesem Abschnitt beschriebenen Informationen sind im Rahmen der Console-Einrichtung zu berücksichtigen, bevor überhaupt mit der Bereitstellung von Cloud Volumes ONTAP begonnen wird.

[cols="20,35,25,25"]
|===
| Aufgabe | Beschreibung | Referenz | Hinweise für Bereitstellungen im privaten Modus 


 a| 
Einen Console-Agenten erstellen
 a| 
Falls noch kein Console-Agent vorhanden ist, sollte dieser vor der Bereitstellung von Cloud Volumes ONTAP erstellt werden. Bei der Bereitstellung in einem Subnetz ohne Internetzugang ist der Console-Agent manuell zu installieren und auf die auf diesem Agenten ausgeführte NetApp Console zuzugreifen.
 a| 
Siehe die Anleitung zur Konsoleneinrichtung: https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-aws.html["Einen Console-Agenten in AWS erstellen"^]
 a| 
Bei der Bereitstellung in einem Subnetz ohne Internetzugang ist der Console-Agent manuell zu installieren, und auf die NetApp Console-Benutzeroberfläche zuzugreifen, die auf diesem Console-Agent ausgeführt wird. Im Console-Setup-Leitfaden finden sich weitere Informationen: https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Manuelle Installation des Console Agenten ohne Internetzugang"^]



 a| 
Planen Sie Ihre Konfiguration
 a| 
Die Konsole bietet vorkonfigurierte Pakete, die Ihren Workload-Anforderungen entsprechen, oder Sie können Ihre eigene Konfiguration erstellen.  Wenn Sie Ihre eigene Konfiguration auswählen, sollten Sie die Ihnen zur Verfügung stehenden Optionen verstehen.
 a| 
link:task-planning-your-config.html["Planen Sie Ihre Konfiguration"]
 a| 
Für Bereitstellungen im privaten Modus sind ähnliche Planungsüberlegungen erforderlich.



 a| 
Richten Sie Ihr Netzwerk ein
 a| 
. Es sollte sichergestellt sein, dass Ihre VPC und Subnetze die Konnektivität zwischen dem Console Agent und Cloud Volumes ONTAP unterstützen.
. Ausgehender Internetzugang für AutoSupport wird ermöglicht.
. Ein VPC-Endpunkt zu Amazon S3 für das Data Tiering kann eingerichtet werden. Ein VPC-Endpunkt ist erforderlich, wenn kalte Daten von Cloud Volumes ONTAP in kostengünstigen Objektspeicher ausgelagert werden sollen.

 a| 
link:reference-networking-aws.html["Netzwerkanforderungen für AWS"]
 a| 
Ausgehender Internetzugang für AutoSupport ist nicht erforderlich. Alle anderen Netzwerkvoraussetzungen bleiben unverändert.



 a| 
Einrichten des AWS KMS
 a| 
Wenn Sie die Amazon-Verschlüsselung mit Cloud Volumes ONTAP verwenden möchten, ist sicherzustellen, dass ein aktiver Customer Master Key (CMK) vorhanden ist, und die Schlüsselrichtlinie ist so zu ändern, dass die IAM-Rolle für den Console Agent als Schlüsselbenutzer hinzugefügt wird.
 a| 
link:task-setting-up-kms.html["Einrichten des AWS KMS"]
 a| 
Ähnliche Schritte gelten für Bereitstellungen im privaten Modus.



 a| 
Cloud Volumes ONTAP über die Konsole bereitstellen
 a| 
Sobald Sie alle Voraussetzungen erfüllt haben, können die Schritte im Assistenten abgeschlossen werden, um Cloud Volumes ONTAP in AWS bereitzustellen.
 a| 
* link:task-quick-deploy-aws.html["Cloud Volumes ONTAP mit Schnellerstellung bereitstellen"]
* link:task-deploying-otc-aws.html["Cloud Volumes ONTAP mit erweiterten Optionen bereitstellen"]

 a| 
Vor Beginn der Bereitstellung ist sicherzustellen, dass eine Cloud Volumes ONTAP Lizenz von NetApp erworben wurde. Für Bereitstellungen im privaten Modus ist eine node-basierte BYOL Lizenz erforderlich. Marketplace-Abonnements werden für die Abrechnung der Cloud Volumes ONTAP Nutzung nicht unterstützt. Die Lizenzdatei ist von NetApp zu beziehen und während der Bereitstellung hochzuladen. Es wird verwiesen auf:

* link:concept-license-management.html["Lizenzverwaltung für knotenbasiertes BYOL"]
* link:task-manage-node-licenses.html["Knotenbasierte BYOL-Lizenzen verwalten"]
* link:task-quick-deploy-aws.html["Cloud Volumes ONTAP mit Schnellerstellung bereitstellen"]
* link:task-deploying-otc-aws.html["Cloud Volumes ONTAP mit erweiterten Optionen bereitstellen"]


|===
.Weiterführende Links
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-bluexp.html["Erstellen Sie einen Konsolenagenten für AWS"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-marketplace.html["Erstellen Sie einen Konsolenagenten aus dem AWS Marketplace"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["Installieren und Einrichten eines Konsolenagenten vor Ort"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-aws.html["AWS-Berechtigungen für den Konsolenagenten"^]

