---
sidebar: sidebar 
permalink: task-verify-autosupport.html 
keywords: autosupport, set up autosupport, test autosupport, asup, test asup 
summary: AutoSupport überwacht proaktiv den Zustand Ihres Systems und sendet Nachrichten an den technischen Support von NetApp .  Standardmäßig ist AutoSupport auf jedem Knoten aktiviert, um Nachrichten über das HTTPS-Transportprotokoll an den technischen Support zu senden.  Am besten überprüfen Sie, ob AutoSupport diese Nachrichten senden kann. 
---
= Überprüfen Sie das AutoSupport -Setup für Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AutoSupport überwacht proaktiv den Zustand Ihres Systems und sendet Nachrichten an den technischen Support von NetApp .  Standardmäßig ist AutoSupport auf jedem Knoten aktiviert, um Nachrichten über das HTTPS-Transportprotokoll an den technischen Support zu senden.  Am besten überprüfen Sie, ob AutoSupport diese Nachrichten senden kann.

Der einzige erforderliche Konfigurationsschritt besteht darin, sicherzustellen, dass Cloud Volumes ONTAP über eine ausgehende Internetverbindung verfügt.  Einzelheiten finden Sie in den Netzwerkanforderungen Ihres Cloud-Anbieters.



== AutoSupport Anforderungen

Cloud Volumes ONTAP -Knoten erfordern ausgehenden Internetzugang für NetApp AutoSupport, das den Zustand Ihres Systems proaktiv überwacht und Nachrichten an den technischen Support von NetApp sendet.

Routing- und Firewall-Richtlinien müssen HTTPS-Verkehr zu den folgenden Endpunkten zulassen, damit Cloud Volumes ONTAP AutoSupport Nachrichten senden kann:

* \https://mysupport.netapp.com/aods/asupmessage
* \https://mysupport.netapp.com/asupprod/post/1.0/postAsup


Wenn zum Senden von AutoSupport -Nachrichten keine ausgehende Internetverbindung verfügbar ist, konfiguriert die NetApp Console Ihre Cloud Volumes ONTAP Systeme automatisch so, dass der Konsolenagent als Proxyserver verwendet wird.  Die einzige Voraussetzung besteht darin, sicherzustellen, dass die Sicherheitsgruppe des Konsolenagenten _eingehende_ Verbindungen über Port 3128 zulässt. Sie müssen diesen Port öffnen, nachdem Sie den Konsolenagenten bereitgestellt haben.

Wenn Sie strenge ausgehende Regeln für Cloud Volumes ONTAP definiert haben, müssen Sie auch sicherstellen, dass die Sicherheitsgruppe Cloud Volumes ONTAP ausgehende Verbindungen über Port 3128 zulässt.


TIP: Wenn Sie ein HA-Paar verwenden, benötigt der HA-Mediator keinen ausgehenden Internetzugang.

Nachdem Sie überprüft haben, dass ausgehender Internetzugang verfügbar ist, können Sie AutoSupport testen, um sicherzustellen, dass es Nachrichten senden kann.  Anweisungen hierzu finden Sie im https://docs.netapp.com/us-en/ontap/system-admin/setup-autosupport-task.html["ONTAP -Dokumentation: AutoSupport einrichten"^] .



== Fehlerbehebung bei Ihrer AutoSupport -Konfiguration

Wenn keine ausgehende Verbindung verfügbar ist und die Konsole Ihr Cloud Volumes ONTAP -System nicht so konfigurieren kann, dass der Konsolenagent als Proxy-Server verwendet wird, erhalten Sie von der Konsole eine Benachrichtigung, dass Ihr System nicht in der Lage ist, AutoSupport Nachrichten zu senden. Befolgen Sie diese Schritte, um dieses Problem zu beheben.

.Schritte
. Stellen Sie eine sichere Verbindung (über SSH) zum Cloud Volumes ONTAP System her, um die ONTAP CLI zu verwenden.
+
link:task-connecting-to-otc.html["Erfahren Sie, wie Sie per SSH auf Cloud Volumes ONTAP zugreifen"] .

. Überprüfen Sie den detaillierten Status des AutoSupport Subsystems:
+
`autosupport check show-details`

+
Die Antwort sieht folgendermaßen aus:

+
[listing]
----
    Category: smtp
          Component: mail-server
             Status: failed
             Detail: SMTP connectivity check failed for destination:
                     mailhost. Error: Could not resolve host - 'mailhost'
            Corrective Action: Check the hostname of the SMTP server

    Category: http-https
        Component: http-put-destination
            Status: ok
            Detail: Successfully connected to:
                    <https://support.netapp.com/put/AsupPut/>.

          Component: http-post-destination
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/asupprod/post/1.0/postAsup.

    Category: on-demand
          Component: ondemand-server
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/aods/asupmessage.

    Category: configuration
            Component: configuration
                Status: ok
                Detail: No configuration issues found.
    5 entries were displayed.
----
+
Wenn der Status der Kategorie http-https ist `OK` Das bedeutet, dass AutoSupport ordnungsgemäß konfiguriert ist und Nachrichten gesendet werden können.

. Falls nicht, überprüfen Sie die Proxy-URL für jeden Cloud Volumes ONTAP -Knoten:
+
`autosupport show -fields proxy-url`

. Wenn der Proxy-URL-Parameter leer ist, konfigurieren Sie Cloud Volumes ONTAP so, dass der Konsolenagent als Proxy verwendet wird:
+
`autosupport modify -proxy-url \http://<console agent private ip>:3128`

. Überprüfen Sie den AutoSupport Status erneut:
+
`autosupport check show-details`

. Wenn der Status weiterhin „Fehlgeschlagen“ lautet, überprüfen Sie, ob eine Verbindung zwischen Cloud Volumes ONTAP und dem Konsolenagenten über Port 10 besteht. `3128`Die
. Wenn der Status nach der Überprüfung immer noch fehlgeschlagen ist, stellen Sie eine SSH-Verbindung zum Konsolenagenten her.
+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-maintain-connectors.html#connect-to-the-linux-vm["Erfahren Sie mehr über die Verbindung zur Linux-VM für den Konsolen-Agenten"^]

. Gehe zu `/opt/application/netapp/cloudmanager/docker_occm/data/`Die
. Öffnen Sie die Proxy-Konfigurationsdatei `squid.conf`Die Dies ist die Struktur der Datei:
+
[listing]
----
        http_port 3128
        acl netapp_support dst support.netapp.com
        http_access allow netapp_support
        request_header_max_size 21 KB
        reply_header_max_size 21 KB
        http_access deny all
        httpd_suppress_version_string on
----
. Falls Ihre Datei keinen Eintrag für den CIDR-Block des Cloud Volumes ONTAP Systems enthält, fügen Sie einen neuen Eintrag hinzu und erlauben Sie den Zugriff:
+
`acl cvonet src <cidr>`

+
`http_access allow cvonet`

+
Hier ist ein Beispiel:

+
[listing]
----
        http_port 3128
        acl netapp_support dst support.netapp.com
        acl cvonet src <cidr>
        http_access allow netapp_support
        http_access allow cvonet
        request_header_max_size 21 KB
        reply_header_max_size 21 KB
        http_access deny all
        httpd_suppress_version_string on

----
. Nach der Bearbeitung der Konfigurationsdatei muss der Proxy-Container neu gestartet werden. `sudo`Die Je nachdem, ob Sie Docker oder Podman verwenden, führen Sie folgende Befehle aus:
+
Für Docker: Führen Sie Folgendes aus `docker restart squid`Die

+
Wenn Sie Podman verwenden, führen Sie Folgendes aus: `podman restart squid`Die

. Kehren Sie zur ONTAP CLI zurück und überprüfen Sie, ob Cloud Volumes ONTAP AutoSupport Nachrichten senden kann:
+
`autosupport check show-details`



.Weiterführende Links
* link:reference-networking-aws.html["Netzwerkanforderungen für Cloud Volumes ONTAP in AWS"^]
* link:reference-networking-azure.html["Netzwerkanforderungen für Cloud Volumes ONTAP in Azure"^]
* link:reference-networking-gcp.html["Netzwerkanforderungen für Cloud Volumes ONTAP in Google Cloud"^]

