---
sidebar: sidebar 
permalink: task-file-verification-mac.html 
keywords: Azure, image, VHD, file signature verification, encryption, sha256, ONTAP, Cloud Volumes, CLI, macOS 
summary: Überprüfen Sie die Signatur einer exportierten VHD-Datei über das Cloud Volumes ONTAP Image Digest File Tool unter macOS 
---
= Überprüfen der Azure Marketplace-Imagesignatur für Cloud Volumes ONTAP unter macOS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Überprüfung der Signatur einer exportierten VHD-Datei unter Linux umfasst die Validierung der Vertrauenskette, die Bearbeitung der Datei und die Überprüfung der Signatur.

.Schritte
. Laden Sie die Azure-Imagedatei von der https://mysupport.netapp.com/site/["NetApp Support Site"^] und extrahieren Sie die Digest-Datei (.sig), die Public-Key-Zertifikatdatei (.pem) und die Kettenzertifikatdatei (.pem).
+
Siehe https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-azure-download-digest-file.html["Herunterladen der Azure-Image-Digest-Datei"^] für weitere Informationen.

. Überprüfen Sie die Vertrauenskette.
+
[source, cli]
----
% openssl verify -CAfile Certificate-Chain-9.15.0P1_azure.pem Certificate-9.15.0P1_azure.pem
Certificate-9.15.0P1_azure.pem: OK
----
. Entfernen Sie 1 MB (1.048.576 Bytes) am Anfang und 512 Bytes am Ende der VHD-Datei.  Bei der Verwendung `tail` , Die `-c +K` Option generiert Bytes aus dem K-ten Byte der Datei.  Daher geht es 1048577 an `tail -c` .  Beachten Sie, dass die Ausführung des Tail-Befehls unter macOS etwa zehn Minuten dauern kann.
+
[source, cli]
----
% tail -c +1048577 ./9150.01000024.05090105.vhd > ./sign.tmp.tail
% head -c -512 ./sign.tmp.tail > sign.tmp
% rm ./sign.tmp.tail
----
. Verwenden Sie OpenSSL, um den öffentlichen Schlüssel aus dem Zertifikat zu extrahieren und die extrahierte Datei (sign.tmp) mit der Signaturdatei und dem öffentlichen Schlüssel zu überprüfen.  Die Eingabeaufforderung zeigt Meldungen an, die den Erfolg oder Misserfolg der Überprüfung basierend auf deren Erfolg anzeigen.
+
[source, cli]
----
% openssl x509 -pubkey -noout -in ./Certificate-9.15.0P1_azure.pem > ./Code-Sign-Cert-Public-key.pub

% openssl dgst -verify Code-Sign-Cert-Public-key.pub -keyform PEM -sha256 -signature digest.sig -binary ./sign.tmp
Verified OK

% openssl dgst -verify Code-Sign-Cert-Public-key.pub -keyform PEM -sha256 -signature digest.sig -binary ./another_file_from_nowhere.tmp
Verification Failure
----
. Räumen Sie den Arbeitsbereich auf.
+
[source, cli]
----
% rm ./9150.01000024.05090105.vhd ./sign.tmp
% rm *.sig *.pub *.pem
----

