---
sidebar: sidebar 
permalink: task-deploy-cvo-azure-mktplc.html 
keywords: deploy cvo marketplace, marketplace direct cvo deployment, azure marketplace 
summary:  
---
= Cloud Volumes ONTAP aus dem Azure Marketplace bereitstellen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mit der direkten Bereitstellung über den Azure Marketplace lässt sich Cloud Volumes ONTAP schnell und einfach bereitstellen. Über den Azure Marketplace kann Cloud Volumes ONTAP mit wenigen Klicks bereitgestellt und die Kernfunktionen und -fähigkeiten in Ihrer Umgebung erkundet werden.

Weitere Informationen zu diesem Angebot finden Sie unterlink:concept-azure-mktplace-direct.html["Informieren Sie sich über die Angebote von Cloud Volumes ONTAP in der NetApp Console und im Marketplace."] .

.Informationen zu diesem Vorgang
Das über den Azure Marketplace direkt bereitgestellte Cloud Volumes ONTAP System weist diese Eigenschaften auf. Es ist zu beachten, dass sich die Funktionen einer eigenständigen Instanz, die über den Azure Marketplace bereitgestellt wurde, ändern, wenn sie in der NetApp Console erkannt wird.

* Die neueste Cloud Volumes ONTAP -Version (9.16.1 oder höher).
* Für Cloud Volumes ONTAP wird eine kostenlose Lizenz für bis zu 500 GiB bereitgestellte Kapazität ohne NetApp Support und ohne Ablaufdatum bereitgestellt. Kapazitäten über 500 GiB hinaus erfordern eine gültige Lizenzberechtigung und können kostenpflichtig sein. Der vollständige Funktionsumfang von Cloud Volumes ONTAP und erweiterte Verwaltungsfunktionen stehen zur Verfügung, wenn das Cloud Volumes ONTAP-System mit der NetApp Console verbunden ist. Erkennung und Verwaltung über die NetApp Console erfordern ein gültiges Azure Marketplace-Abonnement, das mit dem NetApp Console-Konto verknüpft ist.
* Zwei Knoten, die im Hochverfügbarkeitsmodus (HA) in einer einzigen Verfügbarkeitszone (AZ) konfiguriert und mit Standardseriennummern bereitgestellt sind.  Die Storage-VMs (Storage-VMs) werden in einemlink:concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks["flexibler Orchestrierungsmodus"] .
* Ein Aggregat für die standardmäßig erstellte Instanz.
* Eine verwaltete Premium-SSD-v2-Festplatte mit 500 GiB bereitgestellter Kapazität sowie eine Root- und eine Datenfestplatte.
* Eine bereitgestellte Datenspeicher-VM mit NFS-, CIFS-, iSCSI- und NVMe/TCP-Datendiensten.  Sie können keine zusätzlichen Datenspeicher-VMs hinzufügen.
* Installierte Lizenzen für NFS, CIFS (SMB), iSCSI, Autonomous Ransomware Protection (ARP), SnapLock und SnapMirror.
* https://docs.netapp.com/us-en/ontap/volumes/enable-temperature-sensitive-efficiency-concept.html["ONTAP temperaturempfindliche Speichereffizienz (TSSE)"^], Volume-Verschlüsselung und externe Schlüsselverwaltung standardmäßig aktiviert.
* Diese Funktionen werden nicht unterstützt:
+
** FabricPool -Stufen
** Ändern des Speicher-VM-Typs
** Schnellschreibmodus




.Bevor Sie beginnen
* Wenn geplant ist, das bereitgestellte System in der NetApp Console zu erkennen und zu verwalten, muss das NetApp Console-Konto mit einem gültigen Azure Marketplace-Abonnement verknüpft sein. Die Erkennung des Systems in der NetApp Console erfordert ein gültiges Abonnement.
* Stellen Sie sicher, dass Sie die Netzwerkanforderungen für einlink:concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks["HA-Bereitstellung in einer einzigen AZ"] in Azure. Weitere Informationen finden Sie unter link:reference-networking-azure.html["Einrichten des Azure-Netzwerks für Cloud Volumes ONTAP"] .
* Um Cloud Volumes ONTAP bereitzustellen, muss Ihnen eine dieser Azure-Rollen zugewiesen werden:
+
** Der `contributor` Rolle mit den Standardberechtigungen. Weitere Informationen finden Sie im https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles["Microsoft Azure-Dokumentation: Integrierte Azure-Rollen"^] .
** Eine benutzerdefinierte RBAC-Rolle mit den folgenden Berechtigungen. Weitere Informationen finden Sie im https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles["Azure-Dokumentation: Benutzerdefinierte Azure-Rollen"^] .
+
[]
====
"Berechtigungen": [ { "Aktionen": [ "Microsoft.AAD/register/action", "Microsoft.Resources/subscriptions/resourceGroups/write", "Microsoft.Network/loadBalancers/write", "Microsoft.ClassicCompute/virtualMachines/write", "Microsoft.Compute/capacityReservationGroups/deploy/action", "Microsoft.ClassicCompute/virtualMachines/networkInterfaces/associatedNetworkSecurityGroups/write", "Microsoft.Network/networkInterfaces/write", "Microsoft.Compute/virtualMachines/write", "Microsoft.Compute/virtualMachines/extensions/write", "Microsoft.Resources/deployments/validate/action", "Microsoft.Resources/subscriptions/resourceGroups/read", "Microsoft.Network/virtualNetworks/write", "Microsoft.Network/virtualNetworks/read", "Microsoft.Network/networkSecurityGroups/write", "Microsoft.Network/networkSecurityGroups/read", "Microsoft.Compute/disks/write", "Microsoft.Compute/virtualMachineScaleSets/write", "Microsoft.Resources/deployments/write", "Microsoft.Network/virtualNetworks/subnets/read", "Microsoft.Network/virtualNetworks/subnets/write" ], "notActions": [], "dataActions": [], "notDataActions": [] } ]

====
+

NOTE: Wenn Sie den Ressourcenanbieter "Microsoft.storage" für Ihr Abonnement registriert haben, benötigen Sie nicht die `Microsoft.AAD/register/action` Erlaubnis. Weitere Informationen finden Sie im https://learn.microsoft.com/en-us/azure/role-based-access-control/permissions/storage["Azure-Dokumentation: Azure-Berechtigungen für Speicher"^] .





.Schritte
. Auf der Azure Marketplace-Website nach NetApp Produkten suchen.
. Wählen Sie * NetApp Cloud Volumes ONTAP direct*.
. Klicken Sie auf *Erstellen*, um den Bereitstellungsassistenten zu starten.
. Wählen Sie einen Plan aus.  In der *Plan*-Liste werden normalerweise die neuesten Versionen von Cloud Volumes ONTAP angezeigt.
. Geben Sie auf der Registerkarte *Grundlagen* die folgenden Details an:
+
** *Abonnement*: Wählen Sie ein Abonnement aus.  Die Bereitstellung wird an die Abonnementnummer gekoppelt.
** *Ressourcengruppe*: Verwenden Sie eine vorhandene Ressourcengruppe oder erstellen Sie eine neue.  Ressourcengruppen helfen bei der Zuweisung aller Ressourcen, wie z. B. Festplatten und Speicher-VMs, innerhalb einer einzigen Gruppe für ein Cloud Volumes ONTAP System.
** *Region*: Wählen Sie eine Region aus, die die Azure HA-Bereitstellung in einer einzelnen AZ unterstützt.  Sie sehen in der Liste nur die verfügbaren Regionen.
** *Größe*: Wählen Sie eine Speicher-VM-Größe für die unterstützte verwaltete Premium-SSD-v2-Festplatte aus.
** *Zone*: Wählen Sie eine Zone für die von Ihnen ausgewählte Region aus.
** *Admin-Passwort*: Legen Sie ein Passwort fest.  Mit diesem Admin-Passwort melden Sie sich nach der Bereitstellung am System an.
** *Passwort bestätigen*: Geben Sie zur Bestätigung dasselbe Passwort erneut ein.
+
*** Fügen Sie auf der Registerkarte *Netzwerk* ein virtuelles Netzwerk und ein Subnetz hinzu oder wählen Sie sie aus den Listen aus.
+

NOTE: Um die Einschränkungen von Microsoft Azure einzuhalten, sollten Sie beim Einrichten eines neuen virtuellen Netzwerks ein neues Subnetz erstellen.  Wenn Sie ein vorhandenes Netzwerk auswählen, sollten Sie ebenfalls ein vorhandenes Subnetz auswählen.

*** Um eine vordefinierte Netzwerksicherheitsgruppe auszuwählen, wählen Sie *Ja*.  Wählen Sie *Nein* aus, um eine vordefinierte Azure-Netzwerksicherheitsgruppe mit den erforderlichen Verkehrsregeln zuzuweisen. Weitere Informationen finden Sie unter link:reference-networking-azure.html#security-group-rules["Sicherheitsgruppenregeln für Azure"] .
*** Bestätigen Sie auf der Registerkarte *Erweitert*, ob die beiden für diese Bereitstellung erforderlichen Azure-Funktionen festgelegt wurden. Siehelink:task-saz-feature.html["Aktivieren Sie eine Azure-Funktion für Cloud Volumes ONTAP Single AZ-Bereitstellungen"] Undlink:task-azure-high-availability-mode.html["Aktivieren Sie den Hochverfügbarkeitsmodus für Cloud Volumes ONTAP in Azure"] .
*** Sie können Name-Wert-Paare für die Ressourcen oder Ressourcengruppen auf der Registerkarte *Tags* definieren.
*** Überprüfen Sie auf der Registerkarte *Überprüfen + Erstellen* die Details und starten Sie die Bereitstellung.






.Nach Abschluss
Wählen Sie das Benachrichtigungssymbol aus, um den Fortschritt Ihrer Bereitstellung anzuzeigen.  Nachdem Cloud Volumes ONTAP bereitgestellt wurde, können Sie die für Vorgänge aufgelistete Speicher-VM anzeigen.

Sobald Sie darauf zugreifen können, verwenden Sie ONTAP System Manager oder die ONTAP CLI, um sich mit den von Ihnen festgelegten Administratoranmeldeinformationen bei der Speicher-VM anzumelden.  Anschließend können Sie Volumes, LUNs oder Freigaben erstellen und die Speicherfunktionen von Cloud Volumes ONTAP nutzen.



[[troubleshoot-deployment-issues]]
== Beheben von Bereitstellungsproblemen

Cloud Volumes ONTAP Systeme, die direkt über den Azure Marketplace bereitgestellt werden, beinhalten keinen Support von NetApp. Wenn während der Bereitstellung Probleme auftreten, können diese eigenständig identifiziert und behoben werden.

.Schritte
. Auf der Azure Marketplace-Website zu *Boot diagnostics > Serial log* wechseln.
. Laden Sie die Serienprotokolle herunter und untersuchen Sie sie.
. Informationen zur Fehlerbehebung finden Sie in der Produktdokumentation und in den Knowledge Base-Artikeln (KB).
+
** https://learn.microsoft.com/en-us/partner-center/["Azure Marketplace Dokumentation"]
** https://www.netapp.com/support-and-training/documentation/["NetApp Dokumentation"]
** https://kb.netapp.com/["NetApp KB-Artikel"]






[[discover-the-deployed-systems-in-console]]
== Entdecken Sie die bereitgestellten Systeme in der Konsole

Sie können die Cloud Volumes ONTAP Systeme, die Sie über die direkte Bereitstellung im Azure Marketplace bereitgestellt haben, auf der Seite *Systeme* in der Console entdecken und verwalten. Der Console Agent erkennt die Systeme, fügt sie hinzu, wendet die erforderlichen Lizenzen an und schaltet den vollen Funktionsumfang der Console für diese Systeme frei. Die ursprüngliche HA Konfiguration in einer einzelnen AZ mit PSSD v2 Managed Disks bleibt erhalten, und das System wird für dasselbe Azure Abonnement und dieselbe Ressourcengruppe wie die ursprüngliche Bereitstellung registriert.

.Informationen zu diesem Vorgang
Beim Erkennen der über Azure Marketplace Direct Deployment bereitgestellten Cloud Volumes ONTAP-Systeme führt der Console-Agent folgende Aufgaben aus:

* Ersetzt die freien Lizenzen der ermittelten Systeme als reguläre kapazitätsbasiertelink:concept-licensing.html#packages["Freemium-Lizenzen"] .
* Behält die vorhandenen Funktionen der bereitgestellten Systeme bei und fügt die zusätzlichen Funktionen der Konsole hinzu, z. B. Datenschutz, Datenverwaltung und Sicherheitsfunktionen.
* Ersetzt die installierten Lizenzen auf den Knoten durch neue ONTAP -Lizenzen für NFS, CIFS (SMB), iSCSI, ARP, SnapLock und SnapMirror.
* Konvertiert die generischen Knotenseriennummern in eindeutige Seriennummern.
* Weist den Ressourcen nach Bedarf neue System-Tags zu.
* Wandelt die dynamischen IP-Adressen der Instanz in statische IP-Adressen um.
* Ermöglicht die Funktionalitäten vonlink:task-tiering.html["FabricPool -Stufen"] ,link:task-verify-autosupport.html["AutoSupport"] , Undlink:concept-worm.html["Einmal schreiben, oft lesen"] (WORM)-Speicher auf den bereitgestellten Systemen.  Sie können diese Funktionen bei Bedarf über die Konsole aktivieren.
* Registriert die Instanzen bei den NSS-Konten, die zu ihrer Erkennung verwendet werden.
* Aktiviert Kapazitätsmanagementfunktionen inlink:concept-storage-management.html#capacity-management["automatischer und manueller Modus"] für die entdeckten Systeme.


.Bevor Sie beginnen
Die Bereitstellung muss im Azure Marketplace abgeschlossen sein. Der Console-Agent kann die Systeme nur erkennen, wenn die Bereitstellung abgeschlossen ist und sie zur Erkennung verfügbar sind.

.Schritte
In der Konsole folgen Sie dem Standardverfahren zum Erkennen vorhandener Systeme. Weitere Informationen finden Sie unter link:task-adding-systems.html["Fügen Sie der Konsole ein vorhandenes Cloud Volumes ONTAP -System hinzu"] .


CAUTION: Während der Erkennung können Fehlermeldungen angezeigt werden, diese können jedoch ignoriert werden, bis der Erkennungsprozess abgeschlossen ist. Die systemgenerierten Cloud Volumes ONTAP Konfigurationen im Azure Marketplace Portal sollten während der Erkennung, insbesondere die Systemtags, nicht geändert werden. Jegliche Änderungen an diesen Konfigurationen können zu unerwartetem Systemverhalten führen.

.Nach Abschluss
Nachdem die Erkennung abgeschlossen ist, können Sie die auf der Seite *Systeme* in der Konsole aufgelisteten Systeme anzeigen.  Sie können verschiedene Verwaltungsaufgaben ausführen, wie zum Beispiellink:task-manage-aggregates.html["Erweiterung des Aggregats"] ,link:task-create-volumes.html["Hinzufügen von Volumes"] ,link:task-managing-svms-azure.html["Bereitstellung zusätzlicher Speicher-VMs"] , Undlink:task-change-azure-vm.html["Ändern der Instanztypen"] .

.Weiterführende Links
Weitere Informationen zum Erstellen von Speicher finden Sie in der ONTAP -Dokumentation:

* https://docs.netapp.com/us-en/console-licenses-subscriptions/task-manage-subscriptions.html["Ein neues Marketplace-Abonnement hinzufügen"^]
* https://docs.netapp.com/us-en/ontap/volumes/create-volume-task.html["Erstellen von Volumes für NFS"^]
* https://docs.netapp.com/us-en/ontap-cli/lun-create.html["Erstellen von LUNs für iSCSI"^]
* https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-share-create.html["Freigaben für CIFS erstellen"^]

