---
sidebar: sidebar 
permalink: task-getting-started-gcp.html 
keywords: google cloud platform, gcp, cloud manager, deploy the Console, launch the Console, create the Console, getting started, networking, gcp networking, service account, tiering, data tiering, bucket, fabricpool, cloud backup, storage access key, gcp role, role, iam role, permissions, gcp permissions, cloud backup, the Console 
summary: Beginnen Sie in wenigen Schritten mit Cloud Volumes ONTAP für Google Cloud. 
---
= Bereitstellungsübersicht für Cloud Volumes ONTAP in Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Für die Bereitstellung von Cloud Volumes ONTAP benötigen Sie zunächst Informationen zu Ihrem Google Cloud-Abonnement und zu Cloud Volumes ONTAP-Lizenzen. Es ist außerdem zu prüfen, dass ein NetApp Console-Agent für Ihr Google Cloud-Projekt und Ihre Organisation erstellt wurde. Viele der in diesem Abschnitt beschriebenen Informationen sind im Rahmen der Console-Einrichtung zu berücksichtigen, bevor überhaupt mit der Bereitstellung von Cloud Volumes ONTAP begonnen wird.

[cols="20,35,25,25"]
|===
| Aufgabe | Beschreibung | Referenz | Hinweise für Bereitstellungen im privaten Modus 


 a| 
Einen Console-Agenten erstellen
 a| 
Falls noch kein Console-Agent vorhanden ist, sollte dieser vor der Bereitstellung von Cloud Volumes ONTAP erstellt werden. Bei der Bereitstellung in einem Subnetz ohne Internetzugang ist der Console-Agent manuell zu installieren und auf die auf diesem Agenten ausgeführte NetApp Console zuzugreifen.
 a| 
Siehe die Anleitung zur Konsoleneinrichtung: https://docs.netapp.com/us-en/console-setup-admin/task-install-agent-google-gcloud.html["Einen Console Agent in Google Cloud erstellen"^]
 a| 
Bei der Bereitstellung in einem Subnetz ohne Internetzugang ist der Console-Agent manuell zu installieren, und auf die NetApp Console-Benutzeroberfläche zuzugreifen, die auf diesem Console-Agent ausgeführt wird. Im Console-Setup-Leitfaden finden sich weitere Informationen: https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Manuelle Installation des Console Agenten ohne Internetzugang"^]



 a| 
Planen Sie Ihre Konfiguration
 a| 
Die Konsole bietet vorkonfigurierte Pakete, die Ihren Workload-Anforderungen entsprechen, oder Sie können Ihre eigene Konfiguration erstellen.  Wenn Sie Ihre eigene Konfiguration auswählen, sollten Sie die Ihnen zur Verfügung stehenden Optionen verstehen.
 a| 
link:task-planning-your-config-gcp.html["Planen Sie Ihre Konfiguration"]
 a| 
Für Bereitstellungen im privaten Modus sind ähnliche Planungsüberlegungen erforderlich.



 a| 
Richten Sie Ihr Netzwerk ein
 a| 
. Stellen Sie sicher, dass Ihr VPC und Ihre Subnetze die Konnektivität zwischen dem Konsolenagenten und Cloud Volumes ONTAP unterstützen.
. Wenn eine Daten-Tiering-Funktion aktiviert werden soll, ist das Cloud Volumes ONTAP Subnetz für Private Google Access zu konfigurieren.
. Wenn Sie ein HA-Paar bereitstellen, stellen Sie sicher, dass Sie über vier VPCs verfügen, jede mit ihrem eigenen Subnetz.
. Wenn Sie eine gemeinsam genutzte VPC verwenden, weisen Sie dem Dienstkonto des Konsolenagenten die Rolle „Compute Network User“ zu.
. Aktivieren Sie den ausgehenden Internetzugriff vom Ziel-VPC für NetApp AutoSupport.

 a| 
Siehe:

* link:reference-networking-gcp.html["Netzwerkanforderungen für Google Cloud"]
* Weitere Informationen finden Sie in der Google Cloud-Dokumentation: https://cloud.google.com/vpc/docs/configure-private-google-access["Privater Google-Zugriff konfigurieren"^]

 a| 
Ausgehender Internetzugang für AutoSupport ist nicht erforderlich. Alle anderen Netzwerkvoraussetzungen bleiben unverändert.



 a| 
Ein Servicekonto einrichten
 a| 
Cloud Volumes ONTAP benötigt ein Google Cloud-Dienstkonto, um Data Tiering zu aktivieren, damit kalte Daten in kostengünstigen Objektspeicher in Google Cloud ausgelagert werden können, und auch um NetApp Backup and Recovery zu aktivieren, damit Volumes in kostengünstigen Objektspeicher gesichert werden können.
 a| 
* link:task-creating-gcp-service-account.html["Ein Servicekonto einrichten"]
* link:concept-data-tiering.html["Informationen zum Data Tiering"]
* Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["NetApp Backup and Recovery-Dokumente"^]

 a| 
Für Bereitstellungen im privaten Modus sind keine weiteren Überlegungen erforderlich.



 a| 
Google Cloud APIs aktivieren
 a| 
Aktivieren Sie die erforderlichen Google Cloud APIs in Ihrem Projekt. Diese könnten bereits im Rahmen der Erstellung des Console Agenten aktiviert worden sein.
 a| 
Siehe die Google Cloud Dokumentation: https://cloud.google.com/apis/docs/getting-started#enabling_apis["Google Cloud APIs aktivieren"^]
 a| 
APIs müssen aktiviert sein. Mit dem Cloud-Administrator kann die Aktivierung der erforderlichen APIs in der privaten Umgebung erfolgen.



 a| 
Cloud Volumes ONTAP über die Konsole bereitstellen
 a| 
Wenn alle Voraussetzungen erfüllt sind, lassen sich die Schritte im Assistenten ausführen, um Cloud Volumes ONTAP in Google Cloud bereitzustellen.
 a| 
Siehe:

* link:task-quick-deploy-gcp.html["Cloud Volumes ONTAP mit Schnellerstellung bereitstellen"]
* link:task-deploying-gcp.html["Cloud Volumes ONTAP mit erweiterten Optionen bereitstellen"]

 a| 
Vor Beginn der Bereitstellung ist sicherzustellen, dass eine Cloud Volumes ONTAP Lizenz von NetApp erworben wurde. Für Bereitstellungen im privaten Modus ist eine node-basierte BYOL Lizenz erforderlich. Marketplace-Abonnements werden für die Abrechnung der Cloud Volumes ONTAP Nutzung nicht unterstützt. Die Lizenzdatei ist von NetApp zu beziehen und während der Bereitstellung hochzuladen. Es wird verwiesen auf:

* link:concept-license-management.html["Lizenzverwaltung für knotenbasiertes BYOL"]
* link:task-manage-node-licenses.html["Knotenbasierte BYOL-Lizenzen verwalten"]
* link:task-quick-deploy-gcp.html["Cloud Volumes ONTAP mit Schnellerstellung bereitstellen"]
* link:task-deploying-gcp.html["Cloud Volumes ONTAP mit erweiterten Optionen bereitstellen"]


|===
.Weiterführende Links
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-google.html["Erstellen eines Konsolenagenten"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["Installieren der Konsolenagentensoftware auf einem Linux-Host"^]
* https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html["Google Cloud-Berechtigungen für den Konsolenagenten"^]

