---
sidebar: sidebar 
permalink: task-getting-started-azure.html 
keywords: microsoft, azure, netapp, data fabric, hybrid cloud, cloud, public cloud, networking, marketplace, virtual machine, vnet, quick, getting started, install, installing, deploy, deploying, setup, setting up, launching, requirements, prerequisites, cloud central, permissions, custom role, role, json, permissions, virtual machine, connectivity, internet, outbound, endpoint, connection, networks, vpn, replicating, policy, iam, setupasservice, sign up, cloud manager, BlueXP, cloud volumes ontap, cloud ontap, subscription, create 
summary: Beginnen Sie in wenigen Schritten mit Cloud Volumes ONTAP für Azure. 
---
= Bereitstellungsübersicht für Cloud Volumes ONTAP in Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Für die Bereitstellung von Cloud Volumes ONTAP benötigen Sie zunächst Informationen zu Ihrem Azure-Abonnement und zu Cloud Volumes ONTAP-Lizenzen. Es ist außerdem zu überprüfen, dass ein NetApp Console-Agent für Ihr Azure-Abonnement und Ihre Organisation erstellt wurde. Viele der in diesem Thema beschriebenen Informationen sind im Rahmen der Console-Einrichtung bereitzustellen, bevor überhaupt mit der Bereitstellung von Cloud Volumes ONTAP begonnen wird.

[cols="20,35,25,25"]
|===
| Aufgabe | Beschreibung | Referenz | Hinweise für Bereitstellungen im privaten Modus 


 a| 
Einen Console-Agenten erstellen
 a| 
Falls Sie noch keinen Console-Agenten besitzen, sollte einer erstellt werden, bevor Cloud Volumes ONTAP bereitgestellt wird.
 a| 
Siehe die Anleitung zur Konsoleneinrichtung: https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-azure.html["Einen Console-Agent in Azure erstellen"^]
 a| 
Bei der Bereitstellung in einem Subnetz ohne Internetzugang ist der Console-Agent manuell zu installieren, und auf die NetApp Console-Benutzeroberfläche zuzugreifen, die auf diesem Console-Agent ausgeführt wird. Im Console-Setup-Leitfaden finden sich weitere Informationen: https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Manuelle Installation des Console Agenten ohne Internetzugang"^]



 a| 
Planen Sie Ihre Konfiguration
 a| 
Die Konsole bietet vorkonfigurierte Pakete, die Ihren Workload-Anforderungen entsprechen, oder Sie können Ihre eigene Konfiguration erstellen.  Wenn Sie Ihre eigene Konfiguration auswählen, sollten Sie die Ihnen zur Verfügung stehenden Optionen verstehen.
 a| 
link:task-planning-your-config-azure.html["Planen Sie Ihre Cloud Volumes ONTAP -Konfiguration in Azure"]
 a| 
Für Bereitstellungen im privaten Modus sind ähnliche Planungsüberlegungen erforderlich.



 a| 
Richten Sie Ihr Netzwerk ein
 a| 
. Es sollte sichergestellt sein, dass Ihr VNet und Ihre Subnetze die Konnektivität zwischen dem Console-Agent und Cloud Volumes ONTAP unterstützen.
. Ausgehender Internetzugriff vom Ziel-VNet für NetApp AutoSupport ermöglichen.

 a| 
link:reference-networking-azure.html["Netzwerkanforderungen für Azure"]
 a| 
Ausgehender Internetzugang für AutoSupport ist nicht erforderlich. Alle anderen Netzwerkvoraussetzungen bleiben unverändert.



 a| 
Cloud Volumes ONTAP über die Konsole bereitstellen
 a| 
Nachdem alle Voraussetzungen erfüllt wurden, lassen sich die Schritte im Assistenten ausführen, um Cloud Volumes ONTAP in Azure bereitzustellen.
 a| 
Siehe:

* link:task-quick-deploy-azure.html["Cloud Volumes ONTAP mit Schnellerstellung bereitstellen"]
* link:task-deploying-otc-azure.html["Cloud Volumes ONTAP mit erweiterten Optionen bereitstellen"]

 a| 
Vor Beginn der Bereitstellung ist sicherzustellen, dass eine Cloud Volumes ONTAP Lizenz von NetApp erworben wurde. Für Bereitstellungen im privaten Modus ist eine node-basierte BYOL Lizenz erforderlich. Marketplace-Abonnements werden für die Abrechnung der Cloud Volumes ONTAP Nutzung nicht unterstützt. Die Lizenzdatei ist von NetApp zu beziehen und während der Bereitstellung hochzuladen. Es wird verwiesen auf:

* link:concept-license-management.html["Lizenzverwaltung für knotenbasiertes BYOL"]
* link:task-manage-node-licenses.html["Knotenbasierte BYOL-Lizenzen verwalten"]
* link:task-quick-deploy-azure.html["Cloud Volumes ONTAP mit Schnellerstellung bereitstellen"]
* link:task-deploying-otc-azure.html["Cloud Volumes ONTAP mit erweiterten Optionen bereitstellen"]


|===
.Weiterführende Links
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-azure.html["Erstellen eines Konsolenagenten über die Konsole"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-azure-marketplace.html["Erstellen eines Konsolen-Agenten aus dem Azure Marketplace"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["Installieren der Konsolenagentensoftware auf einem Linux-Host"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-azure.html["Was die Konsole mit Berechtigungen macht"^]

