---
sidebar: sidebar 
permalink: task-connect-lun.html 
keywords: lun, connect lun, iscsi lun, target iqn, iqn 
summary: Wenn Sie ein iSCSI-Volume erstellen, erstellt die NetApp Console automatisch eine LUN für Sie.  Wir haben es einfach gemacht, indem wir nur eine LUN pro Volume erstellt haben, sodass keine Verwaltung erforderlich ist.  Nachdem Sie das Volume erstellt haben, verwenden Sie den IQN, um von Ihren Hosts aus eine Verbindung mit der LUN herzustellen. 
---
= Stellen Sie von Ihrem Hostsystem aus eine Verbindung zu einem LUN auf Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie ein iSCSI-Volume erstellen, erstellt die NetApp Console automatisch eine LUN für Sie.  Wir haben es einfach gemacht, indem wir nur eine LUN pro Volume erstellt haben, sodass keine Verwaltung erforderlich ist.  Nachdem Sie das Volume erstellt haben, verwenden Sie den IQN, um von Ihren Hosts aus eine Verbindung mit der LUN herzustellen.

Beachten Sie Folgendes:

* Die automatische Kapazitätsverwaltung der Konsole gilt nicht für LUNs.  Beim Erstellen einer LUN wird die Autogrow-Funktion deaktiviert.
* Sie können zusätzliche LUNs vom ONTAP System Manager oder der ONTAP CLI erstellen.


.Schritte
. Wählen Sie im linken Navigationsmenü *Speicher > Verwaltung*.
. Doppelklicken Sie auf der Seite *Systeme* auf das Cloud Volumes ONTAP -System, auf dem Sie Volumes verwalten möchten.
. Wählen Sie im System die Registerkarte *Volumes*.
. Gehen Sie zur Kachel des gewünschten Volumes und wählen Sie dann *Volume verwalten* aus, um auf das Bedienfeld „Volumes verwalten“ auf der rechten Seite zuzugreifen.
. Klicken Sie auf *Ziel-iQN*.
. Klicken Sie auf *Kopieren*, um den iQN-Namen zu kopieren.
. Richten Sie eine iSCSI-Verbindung vom Host zur LUN ein.
+
** http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-rhel-cg/GUID-15E8C226-BED5-46D0-BAED-379EA4311340.html["ONTAP 9 iSCSI Express-Konfiguration für Red Hat Enterprise Linux: Starten der iSCSI-Sitzungen mit dem Ziel"^]
** http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-cpg/GUID-857453EC-90E9-4AB6-B543-83827CF374BF.html["ONTAP 9 iSCSI Express-Konfiguration für Windows: Starten von iSCSI-Sitzungen mit dem Ziel"^]
** https://docs.netapp.com/us-en/ontap-sanhost/["ONTAP SAN-Hostkonfiguration"^]



