---
sidebar: sidebar 
permalink: task-sync-time.html 
keywords: set up, setting up, ntp, time, synch 
summary: Durch die Angabe eines NTP-Servers wird die Zeit zwischen den Systemen in Ihrem Netzwerk synchronisiert, wodurch Probleme aufgrund von Zeitunterschieden vermieden werden können. 
---
= Synchronisieren Sie die Systemzeit von Cloud Volumes ONTAP mithilfe von NTP-Servern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Konfiguration von Network Time Protocol (NTP)-Servern für Ihre Cloud Volumes ONTAP-Cluster gewährleistet die präzise Zeitsynchronisierung Ihrer Clusterzeit mit anderen Systemen in Ihrem Netzwerk und externen Servern. Die Synchronisierung Ihrer Clusterzeit mit externen NTP-Servern trägt zur Konsistenz Ihrer gesamten Infrastruktur bei. NetApp konfiguriert standardmäßig NTP-Server für neue Cloud Volumes ONTAP-Bereitstellungen. Sollten diese jedoch für Ihre bestehenden Cloud Volumes ONTAP-Cluster nicht konfiguriert sein, müssen Sie NTP-Server für eine genaue Zeitsynchronisierung innerhalb und außerhalb Ihres Netzwerks einrichten.

Sie können einen NTP-Server wie folgt angeben:

* https://docs.netapp.com/us-en/bluexp-automation/cm/api_ref_resources.html["Die NetApp Console API"^].
* Der ONTAP CLI-Befehl https://docs.netapp.com/us-en/ontap-cli//cluster-time-service-ntp-server-create.html["Cluster-Zeitdienst-NTP-Server erstellen"^]Die



NOTE: Wenn Sie keinen NTP-Server konfigurieren, kann es zu Serviceunterbrechungen und ungenauer Zeitsynchronisierung kommen.

.Weiterführende Links
* Wissensdatenbankartikel (KB): https://kb.netapp.com/Cloud/ncds/nds/cvo/cvo_kbs/How_does_a_CVO_cluster_use_NTP["Wie nutzt ein CVO-Cluster NTP?"]
* https://docs.netapp.com/us-en/bluexp-automation/cm/prepare.html["Vorbereiten der Verwendung der API"^]
* https://docs.netapp.com/us-en/bluexp-automation/cm/workflow_processes.html#organization-of-cloud-volumes-ontap-workflows["Cloud Volumes ONTAP -Workflows"^]
* https://docs.netapp.com/us-en/bluexp-automation/platform/get_identifiers.html#get-the-connector-identifier["Abrufen der erforderlichen Kennungen"^]
* https://docs.netapp.com/us-en/bluexp-automation/platform/use_rest_apis.html["Verwenden Sie die REST-APIs für die NetApp Console"^]

