---
sidebar: sidebar 
permalink: task-aws-key-management.html 
keywords: aws, amazon, encryption, NVE, NetApp volume encryption, KMIP, kms, key manager service 
summary: Nutzen Sie den Schlüsselverwaltungsdienst von AWS für Ihren Schlüsselverwaltungsdienst von Drittanbietern. 
---
= Verwalten Sie Cloud Volumes ONTAP Verschlüsselungsschlüssel mit dem AWS Key Management Service
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Sie könnenlink:https://docs.aws.amazon.com/kms/latest/developerguide/overview.html["Schlüsselverwaltungsdienst (KMS) von AWS"^] um Ihre ONTAP Verschlüsselungsschlüssel in einer von AWS bereitgestellten Anwendung zu schützen.

Die Schlüsselverwaltung mit AWS KMS kann mit der CLI oder der ONTAP REST API aktiviert werden.

Beachten Sie bei der Verwendung des KMS, dass standardmäßig das LIF eines Daten-SVM zur Kommunikation mit dem Cloud-Schlüsselverwaltungsendpunkt verwendet wird.  Zur Kommunikation mit den Authentifizierungsdiensten von AWS wird ein Knotenverwaltungsnetzwerk verwendet.  Wenn das Clusternetzwerk nicht richtig konfiguriert ist, kann der Cluster den Schlüsselverwaltungsdienst nicht richtig nutzen.

.Bevor Sie beginnen
* Cloud Volumes ONTAP muss in der Version 9.12.0 oder höher ausgeführt werden.
* Sie müssen die Volume Encryption (VE)-Lizenz installiert haben und
* Sie müssen die Lizenz Multi-tenant Encryption Key Management (MTEKM) installiert haben.
* Sie müssen ein Cluster- oder SVM-Administrator sein
* Sie müssen über ein aktives AWS-Abonnement verfügen



NOTE: Sie können nur Schlüssel für eine Daten-SVM konfigurieren.



== Konfiguration

.AWS
. Sie müssen einelink:https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#grant["gewähren"^] für den AWS KMS-Schlüssel, der von der IAM-Rolle zur Verwaltung der Verschlüsselung verwendet wird.  Die IAM-Rolle muss eine Richtlinie enthalten, die die folgenden Vorgänge zulässt:
+
** `DescribeKey`
** `Encrypt`
** `Decrypt`Informationen zum Erstellen eines Zuschusses finden Sie unterlink:https://docs.aws.amazon.com/kms/latest/developerguide/create-grant-overview.html["AWS-Dokumentation"^] .


. link:https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-attach-detach.html["Fügen Sie der entsprechenden IAM-Rolle eine Richtlinie hinzu."^]Die Politik sollte die `DescribeKey` , `Encrypt` , Und `Decrypt` Operationen.


.Cloud Volumes ONTAP
. Wechseln Sie zu Ihrer Cloud Volumes ONTAP Umgebung.
. Wechseln Sie zur erweiterten Berechtigungsstufe:
`set -privilege advanced`
. Aktivieren Sie den AWS-Schlüsselmanager:
`security key-manager external aws enable -vserver _data_svm_name_ -region _AWS_region_ -key-id _key_ID_ -encryption-context _encryption_context_`
. Geben Sie bei der entsprechenden Aufforderung den geheimen Schlüssel ein.
. Bestätigen Sie, dass AWS KMS richtig konfiguriert wurde:
`security key-manager external aws show -vserver _svm_name_`

