= Ende der Verfügbarkeit knotenbasierter Lizenzen
:allow-uri-read: 




=== Ende der Verfügbarkeit knotenbasierter Lizenzen

NetApp hat das Ende der Verfügbarkeit (EOA) und des Supports (EOS) der knotenbasierten Lizenzierung von Cloud Volumes ONTAP geplant.  Ab dem 11. November 2024 wurde die begrenzte Verfügbarkeit von knotenbasierten Lizenzen beendet. Der Support für die knotenbasierte Lizenzierung endet am 31. Dezember 2024.  Nach dem EOA Ihrer knotenbasierten Lizenzen sollten Sie mithilfe des BlueXP Lizenzkonvertierungstools auf eine kapazitätsbasierte Lizenzierung umsteigen.

Bei jährlichen oder längerfristigen Verpflichtungen empfiehlt NetApp , dass Sie sich vor dem EOA-Datum oder dem Ablaufdatum der Lizenz an Ihren NetApp -Vertreter wenden, um sicherzustellen, dass die Voraussetzungen für den Übergang erfüllt sind.  Wenn Sie keinen langfristigen Vertrag für einen Cloud Volumes ONTAP Knoten haben und Ihr System mit einem On-Demand-Pay-as-you-go-Abonnement (PAYGO) betreiben, ist es wichtig, Ihre Konvertierung vor dem EOS-Datum zu planen.  Sowohl bei Langzeitverträgen als auch bei PAYGO-Abonnements können Sie das Lizenzkonvertierungstool BlueXP für eine nahtlose Konvertierung verwenden.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#end-of-availability-of-node-based-licenses["Ende der Verfügbarkeit von knotenbasierten Lizenzen"^] https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-convert-node-capacity.html["Konvertieren Sie eine knotenbasierte Cloud Volumes ONTAP -Lizenz in eine kapazitätsbasierte Lizenz"^]



=== Entfernung knotenbasierter Bereitstellungen aus BlueXP

Die Option, Cloud Volumes ONTAP Systeme mithilfe knotenbasierter Lizenzen bereitzustellen, ist auf BlueXP veraltet.  Mit Ausnahme einiger Sonderfälle können Sie für Cloud Volumes ONTAP Bereitstellungen bei keinem Cloud-Anbieter knotenbasierte Lizenzen verwenden.

NetApp erkennt die folgenden besonderen Lizenzierungsanforderungen in Übereinstimmung mit vertraglichen Verpflichtungen und betrieblichen Anforderungen an und wird in diesen Situationen weiterhin knotenbasierte Lizenzen unterstützen:

* Kunden aus dem öffentlichen Sektor der USA
* Bereitstellungen im privaten Modus
* Bereitstellungen von Cloud Volumes ONTAP in AWS in der Region China
* Wenn Sie über eine gültige, nicht abgelaufene By-Node-Lizenz verfügen, bringen Sie Ihre eigene Lizenz mit (BYOL-Lizenz)


https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#end-of-availability-of-node-based-licenses["Ende der Verfügbarkeit von knotenbasierten Lizenzen"^]



=== Hinzufügen einer Cold Tier für Cloud Volumes ONTAP -Daten auf Azure Blob Storage

Mit BlueXP können Sie jetzt eine kalte Ebene auswählen, um die inaktiven Kapazitätsebenendaten im Azure Blob-Speicher zu speichern.  Durch Hinzufügen der kalten Ebene zu den vorhandenen warmen und kalten Ebenen erhalten Sie eine günstigere Speicheroption und eine verbesserte Kosteneffizienz.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html#data-tiering-in-azure["Datentiering in Azure"^]



=== Option zum Einschränken des öffentlichen Zugriffs auf das Speicherkonto für Azure

Sie haben jetzt die Möglichkeit, den öffentlichen Zugriff auf Ihr Speicherkonto für Cloud Volumes ONTAP -Systeme in Azure einzuschränken.  Durch die Deaktivierung des Zugriffs können Sie Ihre private IP-Adresse vor Offenlegung schützen, selbst innerhalb desselben VNet, falls die Sicherheitsrichtlinien Ihres Unternehmens eingehalten werden müssen.  Diese Option deaktiviert auch die Datenschichtung für Ihre Cloud Volumes ONTAP Systeme und ist sowohl auf einzelne Knoten als auch auf Hochverfügbarkeitspaare anwendbar.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-azure.html#security-group-rules["Sicherheitsgruppenregeln"^] .



=== WORM-Aktivierung nach der Bereitstellung von Cloud Volumes ONTAP

Sie haben jetzt die Möglichkeit, mithilfe von BlueXP den WORM-Speicher (Write Once, Read Many) auf einem vorhandenen Cloud Volumes ONTAP System zu aktivieren.  Diese Funktion bietet Ihnen die Flexibilität, WORM in einer Arbeitsumgebung zu aktivieren, auch wenn WORM bei der Erstellung nicht aktiviert war.  Nach der Aktivierung können Sie WORM nicht mehr deaktivieren.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-worm.html#enabling-worm-on-a-cloud-volumes-ontap-working-environment["Aktivieren von WORM in einer Cloud Volumes ONTAP Arbeitsumgebung"^]
