= Benutzerauthentifizierung für den Zugriff auf System Manager von BlueXP aktiviert
:allow-uri-read: 




=== Benutzerauthentifizierung für den Zugriff auf System Manager von BlueXP aktiviert

Als BlueXP -Administrator können Sie jetzt die Authentifizierung für ONTAP -Benutzer aktivieren, die von BlueXP aus auf ONTAP System Manager zugreifen.  Sie können diese Option aktivieren, indem Sie die BlueXP Connector-Einstellungen bearbeiten.  Diese Option ist für den Standard- und den privaten Modus verfügbar.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-administer-advanced-view.html["Verwalten Sie Cloud Volumes ONTAP mit System Manager"^] .



=== BlueXP Advanced View wurde in System Manager umbenannt

Die Option zur erweiterten Verwaltung von Cloud Volumes ONTAP von BlueXP über ONTAP System Manager wurde von *Advanced View* in *System Manager* umbenannt.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-administer-advanced-view.html["Verwalten Sie Cloud Volumes ONTAP mit System Manager"^] .



=== Einführung einer einfacheren Möglichkeit zur Lizenzverwaltung mit der BlueXP digital wallet

Jetzt können Sie die Verwaltung von Cloud Volumes ONTAP Lizenzen mithilfe verbesserter Navigationspunkte in der BlueXP digital wallet vereinfachen:

* Greifen Sie einfach über die Registerkarten *Verwaltung > Lizenzen und Abonnements > Übersicht/Direktlizenzen* auf Ihre Cloud Volumes ONTAP -Lizenzinformationen zu.
* Klicken Sie im Cloud Volume ONTAP Bereich auf der Registerkarte *Übersicht* auf *Anzeigen*, um einen umfassenden Überblick über Ihre kapazitätsbasierten Lizenzen zu erhalten.  Diese erweiterte Ansicht bietet detaillierte Einblicke in Ihre Lizenzen und Abonnements.
* Wenn Sie die vorherige Benutzeroberfläche bevorzugen, können Sie auf die Schaltfläche *Zur alten Ansicht wechseln* klicken, um die Lizenzdetails nach Typ anzuzeigen und die Abrechnungsmethoden für Ihre Lizenzen zu ändern.


link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-capacity-licenses.html["Kapazitätsbasierte Lizenzen verwalten"^] .
