= Benutzerauthentifizierung für den Zugriff auf System Manager von BlueXP aktiviert
:allow-uri-read: 




[[user-authentication-enabled-for-accessing-system-manager-from-bluexp]]
=== Benutzerauthentifizierung für den Zugriff auf System Manager von BlueXP aktiviert

Als BlueXP -Administrator können Sie jetzt die Authentifizierung für ONTAP -Benutzer aktivieren, die von BlueXP aus auf ONTAP System Manager zugreifen.  Sie können diese Option aktivieren, indem Sie die BlueXP Connector-Einstellungen bearbeiten.  Diese Option ist für den Standard- und den privaten Modus verfügbar.

link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-administer-advanced-view.html["Verwalten Sie Cloud Volumes ONTAP mit System Manager"^].



[[bluexp-advanced-view-renamed-to-system-manager]]
=== BlueXP Advanced View wurde in System Manager umbenannt

Die Option zur erweiterten Verwaltung von Cloud Volumes ONTAP von BlueXP über ONTAP System Manager wurde von *Advanced View* in *System Manager* umbenannt.

link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-administer-advanced-view.html["Verwalten Sie Cloud Volumes ONTAP mit System Manager"^].



[[introducing-a-simpler-way-to-manage-licenses-with-the-bluexp-digital-wallet]]
=== Einführung einer einfacheren Möglichkeit zur Lizenzverwaltung mit der BlueXP digital wallet

Jetzt können Sie die Verwaltung von Cloud Volumes ONTAP Lizenzen mithilfe verbesserter Navigationspunkte in der BlueXP digital wallet vereinfachen:

* Greifen Sie einfach über die Registerkarten *Verwaltung > Licenses and subscriptions > Übersicht/Direktlizenzen* auf Ihre Cloud Volumes ONTAP -Lizenzinformationen zu.
* Auf dem Cloud Volume ONTAP Panel kann auf der Registerkarte „Übersicht“ die Option „Ansicht“ ausgewählt werden, um ein umfassendes Verständnis Ihrer kapazitätsbasierten Lizenzen zu erhalten. Diese erweiterte Ansicht bietet detaillierte Einblicke in Ihre Lizenzen und Abonnements.
* Wenn Sie die vorherige Benutzeroberfläche bevorzugen, können Sie die Schaltfläche *Switch to legacy view* auswählen, um Lizenzdetails nach Typ anzuzeigen und die Abrechnungsmethoden für Ihre Lizenzen zu ändern.


link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-capacity-licenses.html["Kapazitätsbasierte Lizenzen verwalten"^].
