= Möglichkeit zur Leistungssteigerung von Premium SSD v2-Festplatten in Azure
:allow-uri-read: 




[[ability-to-enhance-performance-of-premium-ssd-v2-disks-in-azure]]
=== Möglichkeit zur Leistungssteigerung von Premium SSD v2-Festplatten in Azure

Sie können die Leistung von Premium SSD v2 Managed Disks in Azure jetzt verbessern, indem Sie die IOPS- und Durchsatzparameter ändern.  Mithilfe dieser Funktion können Sie die Speicherleistung Ihrer Systeme auf Basis Ihrer Arbeitslastanforderungen optimieren.

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-perf-params-azure.html["Verwalten der Premium-SSD-v2-Festplattenleistung für Cloud Volumes ONTAP in Azure"^].



[[overage-charging-for-essentials-licenses-simplified]]
=== Vereinfachte Gebührenberechnung für Essentials-Lizenzen bei Überschreitung des Lizenzumfangs

Bei Cloud Volumes ONTAP Marketplace-Jahresverträgen und privaten Angeboten ist die Berechnung der Überschreitungskosten für Essentials-Lizenzen nun an die Berechnung für Bring-Your-Own License (BYOL) Pakete angeglichen. Bisher wurden Überschreitungen zu den stündlichen Marketplace-Tarifen für das jeweilige Essentials-Paket abgerechnet. Wenn der Marketplace-Jahresvertrag mehrere Essentials-Pakete umfasst, berechnet die NetApp Console Überschreitungskosten für ein Essentials-Paket auf Basis der verfügbaren Kapazität eines höherpreisigen Essentials-Pakets im Abonnement. Dadurch wird die Berechnung der Überschreitungskosten für Essentials-Pakete vereinfacht und ein reibungsloser Übergang vom BYOL-Lizenzmodell zu einem abonnementbasierten Modell sichergestellt.

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing-charging.html#how-overages-are-charged-for-essentials-licenses["Wie Überschreitungen bei Essentials-Lizenzen abgerechnet werden"^]



[[support-for-azure-edsv6-sizes-series]]
=== Unterstützung für Azure Edsv6-Größenserien

Ab Cloud Volumes ONTAP 9.17.1 können Sie VMs der Azure Edsv6-Serie über die NetApp Console für neue Cloud Volumes ONTAP Instanzen bereitstellen.  Cloud Volumes ONTAP 9.17.1 und spätere Versionen unterstützen bei neuen Bereitstellungen nur noch VMs der Generation 2.  Diese Geräte der zweiten Generation sind mit den neuesten Technologien kompatibel, wie z. B. Unified Extensible Firmware Interface (UEFI), Azure Boost-Systemen und NVMe.  Sie eignen sich ideal für speicherintensive Systeme und Anwendungen, die einen schnellen, lokalen Speicher benötigen, wie z. B. Datenbankserver und Analyse-Engines.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html#supported-configurations-by-license["Unterstützte Konfigurationen für Cloud Volumes ONTAP in Azure"^]
